mccabe:
  disable:
    - MC0001

pyflakes:
  disable:
    - F401
    - F811
    - F821

pylint:
  disable:
    - chained-comparison
    - django-not-configured  # TODO: check why this warning keeps coming up
    - useless-suppression
