#!/usr/bin/env bash


python3 -m pip install --upgrade PIP SetUpTools

python3 -m pip install --no-cache-dir --upgrade --user \
    https://GitHub.com/VEX-Robotics-AI/RobotMesh-VEX-PyB-API-Stubs/archive/main.zip
