def when_started():
    drivetrain.drive_for(FORWARD, 800, MM)
    drivetrain.turn_for(LEFT, 90, DEGREES)
    drivetrain.drive_for(FORWARD, 800, MM)
    pen.move(DOWN)
    drivetrain.turn_for(LEFT, 110, DEGREES)
    drivetrain.drive_for(FORWARD, 800, MM)
    drivetrain.turn_for(LEFT, 140, DEGREES)
    drivetrain.drive_for(FORWARD, 800, MM)
    pen.move(UP)
    drivetrain.turn_for(RIGHT, 70, DEGREES)
    drivetrain.drive_for(FORWARD, 200, MM)
    pen.move(DOWN)
    drivetrain.drive_for(FORWARD, 300, MM)
    drivetrain.drive_for(REVERSE, 300, MM)
    drivetrain.turn_for(RIGHT, 90, DEGREES)
    drivetrain.drive_for(FORWARD, 375, MM)
    drivetrain.turn_for(LEFT, 90, DEGREES)
    drivetrain.drive_for(FORWARD, 300, MM)
    drivetrain.drive_for(REVERSE, 300, MM)
    drivetrain.turn_for(RIGHT, 90, DEGREES)
    drivetrain.drive_for(FORWARD, 375, MM)
    drivetrain.turn_for(LEFT, 90, DEGREES)
    drivetrain.drive_for(FORWARD, 300, MM)
    pen.move(UP)
    drivetrain.drive_for(FORWARD, 200, MM)
    pen.move(DOWN)
    drivetrain.turn_for(LEFT, 70, DEGREES)
    drivetrain.drive_for(FORWARD, 800, MM)
    drivetrain.turn_for(LEFT, 110, DEGREES)
    pen.move(UP)
    drivetrain.drive_for(FORWARD, 270, MM)
    pen.move(DOWN)
    drivetrain.turn_for(LEFT, 110, DEGREES)
    drivetrain.drive_for(FORWARD, 800, MM)
    pen.move(UP)
    drivetrain.turn_for(RIGHT, 110, DEGREES)
    drivetrain.drive_for(FORWARD, 1200, MM)
    drivetrain.turn_for(LEFT, 90, DEGREES)
    drivetrain.drive_for(FORWARD, 250, MM)
    pen.move(DOWN)
    drivetrain.turn_for(RIGHT, 90, DEGREES)
    for repeat_count in range(45):
        drivetrain.drive_for(FORWARD, 24, MM)
        drivetrain.turn_for(LEFT, 4, DEGREES)
        wait(5, MSEC)
    pen.move(UP)
    drivetrain.drive_for(FORWARD, 300, MM)
    pen.move(DOWN)
    for repeat_count2 in range(90):
        drivetrain.drive_for(FORWARD, 12, MM)
        drivetrain.turn_for(LEFT, 4, DEGREES)
        wait(5, MSEC)
    pen.move(UP)
    drivetrain.drive_for(FORWARD, 450, MM)
    pen.move(DOWN)
    for repeat_count3 in range(90):
        drivetrain.drive_for(FORWARD, 12, MM)
        drivetrain.turn_for(LEFT, 4, DEGREES)
        wait(5, MSEC)
    pen.move(UP)
    drivetrain.drive_for(FORWARD, 175, MM)
    pen.move(DOWN)
    drivetrain.turn_for(LEFT, 90, DEGREES)
    drivetrain.drive_for(FORWARD, 750, MM)
    drivetrain.drive_for(REVERSE, 600, MM)
    drivetrain.turn_for(RIGHT, 90, DEGREES)
    pen.move(UP)
    drivetrain.drive_for(FORWARD, 100, MM)
    pen.move(DOWN)
    drivetrain.drive_for(FORWARD, 350, MM)
    drivetrain.turn_for(LEFT, 90, DEGREES)
    for repeat_count4 in range(45):
        drivetrain.drive_for(FORWARD, 12, MM)
        drivetrain.turn_for(LEFT, 4, DEGREES)
        wait(5, MSEC)
    for repeat_count5 in range(18):
        drivetrain.drive_for(FORWARD, 12, MM)
        drivetrain.turn_for(LEFT, 5, DEGREES)
        wait(5, MSEC)
    drivetrain.drive_for(FORWARD, 200, MM)

vr_thread(when_started())
