#pragma config(Sensor, port3,  EndX,           sensorVexIQ_Touch)
#pragma config(Sensor, port4,  EndY,           sensorVexIQ_Touch)
#pragma config(Motor,  motor2,          MotorX,        tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor5,          MotorY,        tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          MotorPen,      tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

///////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                       //
//   VEX-IQ-Plotter v3     (C) Andreas Dreier / Germany        Please don't hesitate to send me a mail   //
//                             andreas@dreier-privat.de        when you found errors or when you have    //
//   Plotter.Remote.c          21.11.2015                      ideas for improvements ;-)                //
//                                                                                                       //
///////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                       //
//   Necessary parts:                                                                                    //
//                                                                                                       //
//   1 x Super Kit       --> http://www.vexrobotics.com/vexiq/products/kits-bundles/super-kit-eu.html    //
//       P/N: 228-3670                                                                                   //
//                                                                                                       //
//   2 x Gear Add-On kit --> http://www.vexrobotics.com/vexiq/products/accessories/228-2532.html         //
//       P/N: 228-2532                                                                                   //
//                                                                                                       //
///////////////////////////////////////////////////////////////////////////////////////////////////////////


///////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                       //
//   Connections to the VEX-IQ brain:                                                                    //
//                                                                                                       //
//   Port   Type           Function                                                                      //
//   ----   ------------   -------------------------------------------------------------------           //
//    02    Motor          Movement x axis                                                               //
//    03    Touch sensor   Detecting right limitation of x axis                                          //
//    04    Touch sensor   Detecting bottom limitation of y axis                                         //
//    05    Motor          Movement y axis                                                               //
//    06    Motor          Movement pen up and down                                                      //
//                                                                                                       //
///////////////////////////////////////////////////////////////////////////////////////////////////////////

#include "plotBasics.inc"


task main()
{
     int rx;
     int ry;
     int mx;
     int my;

     // Initialize the plotter

     plotInit();

     // Adapt borders for safety (because of manual full speed cross check with phyiscal limitations)

     border_left   = border_left   + 50;
     border_right  = border_right  - 50;
     border_top    = border_top    - 50;
     border_bottom = border_bottom + 50;

     // Instructions on the LCD panel

     drawCircle( 20,32, 11 );
     displayStringAt( 12,35, "A/B" );
     displayStringAt( 0,18, "Position" );

     displayStringAt( 52,39, "F  Pen up" );
     drawLine( 58,33, 62,33 );
     drawLine( 62,33, 60,39 );
     drawLine( 60,39, 58,33 );

     displayStringAt( 52,27, "F  Pen down" );
     drawLine( 58,27, 62,27 );
     drawLine( 62,27, 60,21 );
     drawLine( 60,21, 58,27 );

     // start remote control

     while( 1 )
     {
          ry = vexRT[ ChA ];
          rx = vexRT[ ChB ];

          mx = getMotorEncoder( MotorX ) + X_SIZE;
          my = getMotorEncoder( MotorY );

          if( ( ry < 0             ) &&
              ( my < border_bottom )    )
              ry = 0;

          if( ( ry > 0             ) &&
              ( my > border_top    )    )
              ry = 0;

          if( ( rx < 0             ) &&
              ( mx < border_left   )    )
              rx = 0;

          if( ( rx > 0             ) &&
              ( mx > border_right  )    )
              rx = 0;

          setMotorSpeed( MotorX, rx );
          setMotorSpeed( MotorY, ry );

          if( vexRT[ BtnFUp ] )
              plotPenUp();

          if( vexRT[ BtnFDown ] )
              plotPenDown();

          delay( 5 );
     }
}

//---------------------------------------------------------------------------------------------------------
//   Plotter.Remote.c    ---   End of program
//---------------------------------------------------------------------------------------------------------
