#pragma config(Sensor, port3,  EndX,           sensorVexIQ_Touch)
#pragma config(Sensor, port4,  EndY,           sensorVexIQ_Touch)
#pragma config(Motor,  motor2,          MotorX,        tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor5,          MotorY,        tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          MotorPen,      tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

///////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                       //
//   VEX-IQ-Plotter v3     (C) Andreas Dreier / Germany        Please don't hesitate to send me a mail   //
//                             andreas@dreier-privat.de        when you found errors or when you have    //
//   Plotter.MINION.c          21.11.2015                      ideas for improvements ;-)                //
//                                                                                                       //
///////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                       //
//   Necessary parts:                                                                                    //
//                                                                                                       //
//   1 x Super Kit       --> http://www.vexrobotics.com/vexiq/products/kits-bundles/super-kit-eu.html    //
//       P/N: 228-3670                                                                                   //
//                                                                                                       //
//   2 x Gear Add-On kit --> http://www.vexrobotics.com/vexiq/products/accessories/228-2532.html         //
//       P/N: 228-2532                                                                                   //
//                                                                                                       //
///////////////////////////////////////////////////////////////////////////////////////////////////////////


///////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                       //
//   Connections to the VEX-IQ brain:                                                                    //
//                                                                                                       //
//   Port   Type           Function                                                                      //
//   ----   ------------   -------------------------------------------------------------------           //
//    02    Motor          Movement x axis                                                               //
//    03    Touch sensor   Detecting right limitation of x axis                                          //
//    04    Touch sensor   Detecting bottom limitation of y axis                                         //
//    05    Motor          Movement y axis                                                               //
//    06    Motor          Movement pen up and down                                                      //
//                                                                                                       //
///////////////////////////////////////////////////////////////////////////////////////////////////////////

#include "plotBasics.inc"

///////////////////////////////////////////////////////////////////////////////////////////////////////////


float ms;
int   mx;
int   my;

///////////////////////////////////////////////////////////////////////////////////////////////////////////

void plotLine( int px, int py )
{
     plotLineTo( mx + ms * px, my + ms * py );
}

///////////////////////////////////////////////////////////////////////////////////////////////////////////

void plotMove( int px, int py )
{
     plotMoveTo( mx + ms * px, my + ms * py );
}

///////////////////////////////////////////////////////////////////////////////////////////////////////////

void plotMINION( int x, int y, float scale = 1.0 )
{
     ms = scale;
     mx = x;
     my = y;

     plotMove(   58,  232 );
     plotPenDown();
     plotLine(   12,  262 );
     plotLine(    2,  275 );
     plotLine(    0,  288 );
     plotLine(    2,  297 );
     plotLine(    9,  310 );
     plotLine(   22,  324 );
     plotLine(   45,  344 );
     plotLine(   71,  358 );
     plotLine(   81,  365 );
     plotLine(   89,  375 );
     plotLine(   93,  384 );
     plotPenUp();

     plotMove(   99,  416 );
     plotPenDown();
     plotLine(  101,  445 );
     plotLine(  101,  485 );
     plotLine(   98,  519 );
     plotLine(   94,  544 );
     plotLine(   90,  563 );
     plotLine(   87,  575 );
     plotPenUp();

     plotMove(   72,  653 );
     plotPenDown();
     plotLine(   74,  675 );
     plotLine(   84,  708 );
     plotLine(  102,  743 );
     plotLine(  127,  774 );
     plotLine(  149,  794 );
     plotLine(  173,  810 );
     plotLine(  203,  823 );
     plotLine(  225,  833 );
     plotLine(  251,  839 );
     plotLine(  272,  842 );
     plotLine(  295,  842 );
     plotLine(  317,  842 );
     plotLine(  343,  838 );
     plotLine(  363,  833 );
     plotLine(  395,  820 );
     plotLine(  419,  808 );
     plotLine(  440,  793 );
     plotLine(  455,  783 );
     plotLine(  466,  770 );
     plotLine(  474,  756 );
     plotLine(  482,  742 );
     plotLine(  497,  718 );
     plotPenUp();

     plotMove(  508,  661 );
     plotPenDown();
     plotLine(  520,  624 );
     plotLine(  522,  603 );
     plotLine(  526,  571 );
     plotLine(  528,  538 );
     plotLine(  531,  502 );
     plotLine(  532,  474 );
     plotLine(  533,  459 );
     plotLine(  534,  457 );
     plotPenUp();

     plotMove(  537,  453 );
     plotPenDown();
     plotLine(  542,  492 );
     plotLine(  544,  541 );
     plotLine(  543,  574 );
     plotLine(  542,  599 );
     plotLine(  544,  620 );
     plotPenUp();

     plotMove(  582,  617 );
     plotPenDown();
     plotLine(  583,  585 );
     plotLine(  582,  542 );
     plotLine(  581,  509 );
     plotLine(  580,  460 );
     plotLine(  576,  421 );
     plotLine(  570,  395 );
     plotLine(  559,  356 );
     plotLine(  558,  320 );
     plotLine(  556,  275 );
     plotLine(  551,  244 );
     plotLine(  546,  225 );
     plotPenUp();

     plotMove(  548,  224 );
     plotPenDown();
     plotLine(  500,  237 );
     plotLine(  490,  351 );
     plotLine(  510,  377 );
     plotLine(  523,  394 );
     plotLine(  533,  417 );
     plotLine(  536,  431 );
     plotLine(  537,  446 );
     plotLine(  537,  455 );
     plotLine(  533,  459 );
     plotLine(  521,  441 );
     plotLine(  510,  426 );
     plotLine(  497,  409 );
     plotLine(  488,  402 );
     plotLine(  488,  404 );
     plotLine(  462,  392 );
     plotLine(  433,  387 );
     plotLine(  394,  382 );
     plotLine(  371,  382 );
     plotLine(  339,  383 );
     plotLine(  311,  385 );
     plotLine(  282,  388 );
     plotLine(  250,  392 );
     plotLine(  216,  397 );
     plotLine(  192,  402 );
     plotLine(  192,  393 );
     plotPenUp();

     plotMove(   95,  385 );
     plotPenDown();
     plotLine(   90,  387 );
     plotLine(   92,  410 );
     plotLine(   94,  414 );
     plotLine(  100,  417 );
     plotLine(  115,  415 );
     plotLine(  136,  411 );
     plotLine(  153,  404 );
     plotLine(  168,  400 );
     plotLine(  190,  393 );
     plotLine(  230,  379 );
     plotLine(  222,  340 );
     plotLine(  195,  352 );
     plotLine(  170,  362 );
     plotLine(  145,  371 );
     plotLine(  122,  380 );
     plotLine(  106,  383 );
     plotLine(   93,  385 );
     plotPenUp();

     plotMove(  190,  354 );
     plotPenDown();
     plotLine(  190,  335 );
     plotLine(  192,  300 );
     plotLine(  190,  274 );
     plotLine(  188,  243 );
     plotLine(  172,  243 );
     plotLine(  144,  244 );
     plotLine(  119,  244 );
     plotLine(   91,  244 );
     plotLine(   83,  219 );
     plotLine(   91,  194 );
     plotLine(   94,  180 );
     plotLine(  107,  167 );
     plotLine(  123,  149 );
     plotLine(  139,  137 );
     plotLine(  165,  118 );
     plotLine(  179,  107 );
     plotLine(  190,   94 );
     plotLine(  193,   78 );
     plotLine(  195,   59 );
     plotLine(  198,   45 );
     plotLine(  282,   45 );
     plotLine(  290,   51 );
     plotLine(  290,   61 );
     plotLine(  288,   71 );
     plotLine(  290,   80 );
     plotLine(  303,   85 );
     plotLine(  314,   86 );
     plotLine(  324,   84 );
     plotLine(  330,   75 );
     plotLine(  330,   48 );
     plotLine(  333,   43 );
     plotLine(  338,   42 );
     plotLine(  418,   44 );
     plotLine(  423,   42 );
     plotLine(  427,   52 );
     plotLine(  430,   61 );
     plotLine(  432,   73 );
     plotLine(  444,   86 );
     plotLine(  467,   95 );
     plotLine(  497,  109 );
     plotLine(  514,  122 );
     plotLine(  530,  137 );
     plotLine(  542,  159 );
     plotLine(  548,  180 );
     plotLine(  547,  210 );
     plotLine(  548,  225 );
     plotPenUp();

     plotMove(  532,  156 );
     plotPenDown();
     plotLine(  522,  163 );
     plotLine(  513,  179 );
     plotLine(  510,  195 );
     plotLine(  504,  204 );
     plotPenUp();

     plotMove(  172,  118 );
     plotPenDown();
     plotLine(  190,  115 );
     plotLine(  218,  110 );
     plotLine(  263,  102 );
     plotLine(  296,   94 );
     plotLine(  315,   91 );
     plotLine(  332,   90 );
     plotLine(  362,   88 );
     plotLine(  388,   89 );
     plotLine(  414,   91 );
     plotLine(  438,   91 );
     plotLine(  457,   95 );
     plotPenUp();

     plotMove(  320,   92 );
     plotPenDown();
     plotLine(  328,  101 );
     plotLine(  334,  111 );
     plotLine(  337,  122 );
     plotLine(  342,  135 );
     plotLine(  346,  147 );
     plotPenUp();

     plotMove(  139,  165 );
     plotPenDown();
     plotLine(  154,  170 );
     plotLine(  164,  178 );
     plotLine(  175,  187 );
     plotLine(  180,  200 );
     plotLine(  184,  210 );
     plotPenUp();

     plotMove(  106,  246 );
     plotPenDown();
     plotLine(  104,  261 );
     plotLine(  101,  279 );
     plotLine(   92,  295 );
     plotLine(   83,  302 );
     plotLine(   72,  307 );
     plotLine(   62,  302 );
     plotLine(   52,  297 );
     plotLine(   43,  287 );
     plotLine(   55,  281 );
     plotLine(   67,  275 );
     plotLine(   77,  267 );
     plotLine(   80,  264 );
     plotPenUp();

     plotMove(   43,  287 );
     plotPenDown();
     plotLine(   22,  291 );
     plotPenUp();

     plotMove(  103,  261 );
     plotPenDown();
     plotLine(   97,  265 );
     plotLine(   93,  270 );
     plotLine(   90,  273 );
     plotLine(   79,  264 );
     plotLine(   68,  249 );
     plotLine(   62,  238 );
     plotLine(   55,  223 );
     plotLine(   65,  214 );
     plotLine(   54,  206 );
     plotLine(   50,  198 );
     plotLine(   52,  183 );
     plotLine(   59,  170 );
     plotLine(   69,  161 );
     plotLine(   81,  159 );
     plotLine(   90,  165 );
     plotLine(   95,  168 );
     plotLine(  106,  165 );
     plotPenUp();

     plotMove(  533,  623 );
     plotPenDown();
     plotLine(  543,  620 );
     plotLine(  560,  618 );
     plotLine(  577,  617 );
     plotLine(  589,  619 );
     plotLine(  592,  620 );
     plotLine(  585,  645 );
     plotLine(  585,  658 );
     plotLine(  591,  672 );
     plotLine(  596,  687 );
     plotLine(  605,  692 );
     plotLine(  610,  699 );
     plotLine(  612,  713 );
     plotLine(  606,  724 );
     plotLine(  593,  731 );
     plotLine(  583,  729 );
     plotLine(  573,  721 );
     plotLine(  570,  743 );
     plotLine(  568,  755 );
     plotLine(  562,  768 );
     plotLine(  549,  775 );
     plotLine(  537,  771 );
     plotLine(  529,  765 );
     plotLine(  528,  756 );
     plotLine(  530,  745 );
     plotLine(  535,  736 );
     plotLine(  537,  724 );
     plotLine(  537,  715 );
     plotLine(  533,  705 );
     plotLine(  530,  695 );
     plotLine(  529,  683 );
     plotLine(  533,  676 );
     plotLine(  537,  663 );
     plotLine(  535,  652 );
     plotLine(  534,  625 );
     plotPenUp();

     plotMove(  546,  706 );
     plotPenDown();
     plotLine(  552,  704 );
     plotLine(  558,  707 );
     plotLine(  564,  710 );
     plotLine(  580,  711 );
     plotLine(  587,  705 );
     plotLine(  593,  697 );
     plotLine(  595,  689 );
     plotLine(  592,  681 );
     plotLine(  584,  673 );
     plotLine(  570,  672 );
     plotLine(  558,  673 );
     plotLine(  545,  673 );
     plotPenUp();

     plotMove(  205,  375 );
     plotPenDown();
     plotLine(  206,  362 );
     plotPenUp();

     plotMove(  201,  369 );
     plotPenDown();
     plotLine(  211,  368 );
     plotPenUp();

     plotMove(  214,  381 );
     plotPenDown();
     plotLine(  218,  373 );
     plotLine(  218,  368 );
     plotLine(  214,  360 );
     plotLine(  205,  357 );
     plotLine(  196,  361 );
     plotLine(  191,  367 );
     plotLine(  192,  374 );
     plotLine(  198,  379 );
     plotLine(  202,  381 );
     plotLine(  214,  381 );
     plotPenUp();

     plotMove(  487,  380 );
     plotPenDown();
     plotLine(  484,  380 );
     plotLine(  477,  377 );
     plotLine(  474,  371 );
     plotLine(  473,  363 );
     plotLine(  476,  356 );
     plotLine(  479,  352 );
     plotLine(  484,  352 );
     plotLine(  489,  357 );
     plotLine(  491,  365 );
     plotLine(  491,  373 );
     plotLine(  488,  379 );
     plotPenUp();

     plotMove(  484,  373 );
     plotPenDown();
     plotLine(  483,  361 );
     plotPenUp();

     plotMove(  478,  365 );
     plotPenDown();
     plotLine(  488,  367 );
     plotPenUp();

     plotMove(  490,  400 );
     plotPenDown();
     plotLine(  474,  384 );
     plotLine(  460,  375 );
     plotLine(  463,  359 );
     plotLine(  466,  344 );
     plotLine(  471,  334 );
     plotLine(  479,  340 );
     plotLine(  487,  350 );
     plotLine(  489,  353 );
     plotPenUp();

     plotMove(  300,  336 );
     plotPenDown();
     plotLine(  309,  333 );
     plotLine(  325,  331 );
     plotLine(  342,  328 );
     plotLine(  360,  328 );
     plotLine(  373,  328 );
     plotLine(  386,  327 );
     plotLine(  405,  330 );
     plotLine(  408,  330 );
     plotLine(  410,  261 );
     plotLine(  405,  250 );
     plotLine(  399,  241 );
     plotLine(  389,  233 );
     plotLine(  374,  229 );
     plotLine(  353,  228 );
     plotLine(  334,  230 );
     plotLine(  318,  238 );
     plotLine(  306,  251 );
     plotLine(  300,  273 );
     plotLine(  297,  291 );
     plotLine(  298,  312 );
     plotLine(  298,  338 );
     plotPenUp();

     plotMove(  358,  313 );
     plotPenDown();
     plotLine(  329,  283 );
     plotLine(  360,  248 );
     plotLine(  386,  278 );
     plotLine(  390,  277 );
     plotLine(  390,  268 );
     plotLine(  388,  260 );
     plotLine(  382,  253 );
     plotLine(  373,  246 );
     plotLine(  364,  242 );
     plotLine(  353,  244 );
     plotLine(  340,  249 );
     plotLine(  333,  257 );
     plotLine(  328,  263 );
     plotLine(  325,  273 );
     plotLine(  325,  281 );
     plotLine(  326,  292 );
     plotLine(  329,  305 );
     plotLine(  337,  312 );
     plotLine(  349,  318 );
     plotLine(  357,  320 );
     plotLine(  366,  317 );
     plotLine(  376,  312 );
     plotLine(  382,  307 );
     plotLine(  388,  299 );
     plotLine(  392,  289 );
     plotLine(  392,  282 );
     plotLine(  359,  281 );
     plotLine(  359,  279 );
     plotLine(  367,  278 );
     plotLine(  367,  274 );
     plotLine(  361,  270 );
     plotLine(  355,  271 );
     plotLine(  351,  275 );
     plotLine(  349,  282 );
     plotLine(  349,  288 );
     plotLine(  353,  293 );
     plotLine(  359,  294 );
     plotLine(  364,  291 );
     plotLine(  369,  288 );
     plotLine(  369,  286 );
     plotLine(  384,  286 );
     plotLine(  358,  313 );
     plotPenUp();

     plotMove(  247,  460 );
     plotPenDown();
     plotLine(  310,  465 );
     plotLine(  330,  467 );
     plotLine(  356,  468 );
     plotLine(  388,  468 );
     plotLine(  411,  470 );
     plotLine(  428,  475 );
     plotLine(  441,  479 );
     plotLine(  444,  481 );
     plotLine(  446,  475 );
     plotLine(  445,  464 );
     plotLine(  442,  449 );
     plotLine(  434,  437 );
     plotLine(  424,  423 );
     plotLine(  406,  410 );
     plotLine(  373,  404 );
     plotLine(  341,  402 );
     plotLine(  313,  396 );
     plotLine(  276,  399 );
     plotLine(  251,  408 );
     plotLine(  231,  421 );
     plotLine(  217,  434 );
     plotLine(  208,  447 );
     plotLine(  207,  456 );
     plotLine(  207,  462 );
     plotLine(  211,  465 );
     plotLine(  217,  462 );
     plotLine(  229,  461 );
     plotLine(  247,  460 );
     plotPenUp();

     plotMove(  213,  460 );
     plotPenDown();
     plotLine(  213,  460 );
     plotLine(  216,  448 );
     plotLine(  220,  440 );
     plotLine(  227,  432 );
     plotLine(  233,  430 );
     plotLine(  247,  431 );
     plotLine(  261,  434 );
     plotLine(  275,  439 );
     plotLine(  283,  441 );
     plotLine(  296,  439 );
     plotLine(  307,  440 );
     plotLine(  317,  440 );
     plotLine(  323,  448 );
     plotLine(  325,  462 );
     plotPenUp();

     plotMove(  264,  458 );
     plotPenDown();
     plotLine(  268,  450 );
     plotLine(  274,  445 );
     plotLine(  275,  440 );
     plotPenUp();

     plotMove(  328,  463 );
     plotPenDown();
     plotLine(  329,  453 );
     plotLine(  331,  445 );
     plotLine(  340,  439 );
     plotLine(  350,  439 );
     plotLine(  361,  438 );
     plotLine(  371,  440 );
     plotLine(  378,  443 );
     plotLine(  385,  446 );
     plotLine(  386,  455 );
     plotLine(  387,  464 );
     plotPenUp();

     plotMove(  384,  446 );
     plotPenDown();
     plotLine(  390,  442 );
     plotLine(  398,  440 );
     plotLine(  407,  442 );
     plotLine(  421,  444 );
     plotLine(  429,  448 );
     plotLine(  432,  458 );
     plotLine(  434,  474 );
     plotPenUp();

     plotMove(  280,  400 );
     plotPenDown();
     plotLine(  292,  407 );
     plotLine(  300,  408 );
     plotLine(  308,  409 );
     plotLine(  322,  410 );
     plotLine(  328,  408 );
     plotLine(  333,  403 );
     plotLine(  337,  412 );
     plotLine(  347,  418 );
     plotLine(  357,  421 );
     plotLine(  367,  421 );
     plotLine(  379,  420 );
     plotLine(  385,  417 );
     plotLine(  390,  409 );
     plotLine(  396,  418 );
     plotLine(  406,  420 );
     plotLine(  417,  422 );
     plotPenUp();

     plotMove(  198,   46 );
     plotPenDown();
     plotLine(  198,   44 );
     plotLine(  182,   38 );
     plotLine(  171,   31 );
     plotLine(  167,   26 );
     plotLine(  166,   19 );
     plotLine(  168,   13 );
     plotLine(  165,    9 );
     plotLine(  165,    5 );
     plotLine(  193,    2 );
     plotLine(  222,    2 );
     plotLine(  237,    5 );
     plotLine(  245,    5 );
     plotLine(  248,   10 );
     plotLine(  268,    6 );
     plotLine(  288,    9 );
     plotLine(  288,   16 );
     plotLine(  287,   21 );
     plotLine(  284,   25 );
     plotLine(  284,   34 );
     plotLine(  283,   39 );
     plotLine(  283,   45 );
     plotPenUp();

     plotMove(  168,   14 );
     plotPenDown();
     plotLine(  180,   13 );
     plotLine(  199,   12 );
     plotLine(  219,   13 );
     plotLine(  239,   15 );
     plotLine(  261,   20 );
     plotLine(  281,   27 );
     plotPenUp();

     plotMove(  338,   41 );
     plotPenDown();
     plotLine(  337,   34 );
     plotLine(  337,   31 );
     plotLine(  336,   26 );
     plotLine(  336,   18 );
     plotLine(  334,   15 );
     plotLine(  335,    4 );
     plotLine(  358,    4 );
     plotLine(  380,    5 );
     plotLine(  382,    1 );
     plotLine(  460,    0 );
     plotLine(  464,    7 );
     plotLine(  461,   12 );
     plotLine(  465,   18 );
     plotLine(  461,   26 );
     plotLine(  452,   34 );
     plotLine(  440,   39 );
     plotLine(  427,   42 );
     plotLine(  420,   43 );
     plotPenUp();

     plotMove(  335,   19 );
     plotPenDown();
     plotLine(  348,   21 );
     plotLine(  365,   20 );
     plotLine(  380,   16 );
     plotLine(  403,   15 );
     plotLine(  419,   14 );
     plotLine(  438,   14 );
     plotLine(  459,   13 );
     plotPenUp();

     plotMove(   85,  579 );
     plotPenDown();
     plotLine(   78,  582 );
     plotLine(   68,  593 );
     plotLine(   67,  600 );
     plotLine(   66,  607 );
     plotLine(   65,  615 );
     plotLine(   63,  622 );
     plotLine(   63,  633 );
     plotLine(   66,  646 );
     plotLine(   77,  658 );
     plotLine(  104,  679 );
     plotLine(  111,  658 );
     plotLine(  115,  625 );
     plotLine(  100,  615 );
     plotLine(   90,  607 );
     plotLine(   83,  596 );
     plotLine(   87,  577 );
     plotPenUp();

     plotMove(   67,  610 );
     plotPenDown();
     plotLine(   72,  619 );
     plotLine(   80,  632 );
     plotLine(   89,  642 );
     plotLine(  104,  652 );
     plotLine(  110,  657 );
     plotPenUp();

     plotMove(  107,  660 );
     plotPenDown();
     plotLine(   93,  652 );
     plotLine(   85,  644 );
     plotLine(   77,  637 );
     plotLine(   70,  626 );
     plotLine(   65,  614 );
     plotPenUp();

     plotMove(  103,  679 );
     plotPenDown();
     plotLine(  103,  687 );
     plotLine(  109,  691 );
     plotLine(  114,  708 );
     plotLine(  118,  724 );
     plotLine(  129,  743 );
     plotLine(  144,  759 );
     plotLine(  168,  772 );
     plotLine(  188,  778 );
     plotLine(  205,  779 );
     plotLine(  225,  776 );
     plotLine(  244,  770 );
     plotLine(  263,  759 );
     plotLine(  278,  747 );
     plotLine(  293,  764 );
     plotLine(  309,  779 );
     plotLine(  331,  792 );
     plotLine(  356,  801 );
     plotLine(  382,  802 );
     plotLine(  406,  795 );
     plotLine(  425,  785 );
     plotLine(  439,  772 );
     plotLine(  454,  750 );
     plotLine(  457,  741 );
     plotLine(  460,  720 );
     plotLine(  463,  691 );
     plotLine(  459,  668 );
     plotLine(  452,  653 );
     plotLine(  442,  640 );
     plotLine(  429,  626 );
     plotLine(  415,  614 );
     plotLine(  404,  610 );
     plotLine(  387,  604 );
     plotLine(  373,  604 );
     plotLine(  353,  605 );
     plotLine(  333,  612 );
     plotLine(  314,  622 );
     plotLine(  295,  639 );
     plotLine(  281,  620 );
     plotLine(  264,  605 );
     plotLine(  247,  595 );
     plotLine(  221,  586 );
     plotLine(  190,  587 );
     plotLine(  161,  597 );
     plotLine(  143,  608 );
     plotLine(  131,  622 );
     plotLine(  117,  648 );
     plotLine(  113,  672 );
     plotLine(  112,  691 );
     plotLine(  112,  706 );
     plotPenUp();

     plotMove(  116,  627 );
     plotPenDown();
     plotLine(  130,  620 );
     plotPenUp();

     plotMove(  457,  742 );
     plotPenDown();
     plotLine(  463,  740 );
     plotLine(  466,  731 );
     plotLine(  469,  713 );
     plotLine(  470,  693 );
     plotLine(  472,  680 );
     plotLine(  469,  673 );
     plotLine(  459,  669 );
     plotPenUp();

     plotMove(  471,  678 );
     plotPenDown();
     plotLine(  486,  672 );
     plotLine(  497,  669 );
     plotLine(  505,  663 );
     plotLine(  509,  659 );
     plotLine(  514,  644 );
     plotLine(  517,  635 );
     plotLine(  521,  648 );
     plotLine(  519,  662 );
     plotLine(  519,  669 );
     plotLine(  515,  678 );
     plotLine(  517,  685 );
     plotLine(  516,  694 );
     plotLine(  512,  702 );
     plotLine(  499,  715 );
     plotLine(  480,  724 );
     plotLine(  466,  730 );
     plotPenUp();

     plotMove(  470,  710 );
     plotPenDown();
     plotLine(  484,  703 );
     plotLine(  496,  695 );
     plotLine(  507,  688 );
     plotLine(  515,  678 );
     plotPenUp();

     plotMove(  516,  671 );
     plotPenDown();
     plotLine(  508,  682 );
     plotLine(  494,  690 );
     plotLine(  479,  699 );
     plotLine(  469,  702 );
     plotPenUp();

     plotMove(  277,  685 );
     plotPenDown();
     plotLine(  277,  671 );
     plotLine(  272,  651 );
     plotLine(  262,  634 );
     plotLine(  251,  622 );
     plotLine(  229,  612 );
     plotLine(  204,  608 );
     plotLine(  179,  614 );
     plotLine(  160,  622 );
     plotLine(  144,  639 );
     plotLine(  136,  654 );
     plotLine(  131,  672 );
     plotLine(  130,  690 );
     plotLine(  135,  707 );
     plotLine(  142,  723 );
     plotLine(  155,  737 );
     plotLine(  174,  747 );
     plotLine(  192,  752 );
     plotLine(  213,  754 );
     plotLine(  235,  748 );
     plotLine(  249,  738 );
     plotLine(  261,  727 );
     plotLine(  271,  715 );
     plotLine(  275,  702 );
     plotLine(  277,  684 );
     plotPenUp();

     plotMove(  300,  691 );
     plotPenDown();
     plotLine(  297,  703 );
     plotLine(  300,  725 );
     plotLine(  308,  743 );
     plotLine(  321,  759 );
     plotLine(  336,  768 );
     plotLine(  352,  774 );
     plotLine(  373,  778 );
     plotLine(  391,  775 );
     plotLine(  409,  766 );
     plotLine(  421,  761 );
     plotLine(  434,  743 );
     plotLine(  438,  732 );
     plotLine(  441,  718 );
     plotLine(  441,  701 );
     plotLine(  439,  682 );
     plotLine(  432,  666 );
     plotLine(  420,  649 );
     plotLine(  401,  637 );
     plotLine(  382,  632 );
     plotLine(  358,  633 );
     plotLine(  332,  640 );
     plotLine(  315,  652 );
     plotLine(  307,  667 );
     plotLine(  302,  679 );
     plotLine(  300,  691 );
     plotPenUp();

     plotMove(  183,  670 );
     plotPenDown();
     plotLine(  186,  657 );
     plotLine(  192,  649 );
     plotLine(  204,  643 );
     plotLine(  216,  643 );
     plotLine(  227,  648 );
     plotLine(  232,  656 );
     plotLine(  237,  669 );
     plotLine(  234,  679 );
     plotLine(  228,  688 );
     plotLine(  217,  693 );
     plotLine(  206,  693 );
     plotLine(  195,  689 );
     plotLine(  187,  683 );
     plotLine(  183,  670 );
     plotPenUp();

     plotMove(  344,  686 );
     plotPenDown();
     plotLine(  353,  671 );
     plotLine(  362,  668 );
     plotLine(  379,  666 );
     plotLine(  389,  672 );
     plotLine(  396,  680 );
     plotLine(  399,  691 );
     plotLine(  397,  701 );
     plotLine(  386,  712 );
     plotLine(  374,  716 );
     plotLine(  360,  716 );
     plotLine(  350,  708 );
     plotLine(  346,  702 );
     plotLine(  344,  686 );
     plotPenUp();

     plotMove(   90,  723 );
     plotPenDown();
     plotLine(   79,  724 );
     plotLine(   69,  723 );
     plotLine(   53,  720 );
     plotPenUp();

     plotMove(  121,  751 );
     plotPenDown();
     plotLine(  104,  763 );
     plotLine(   94,  770 );
     plotLine(   83,  774 );
     plotLine(   68,  777 );
     plotPenUp();

     plotMove(  116,  767 );
     plotPenDown();
     plotLine(  102,  772 );
     plotLine(   85,  779 );
     plotLine(   73,  782 );
     plotLine(   59,  782 );
     plotLine(   44,  780 );
     plotPenUp();

     plotMove(  122,  771 );
     plotPenDown();
     plotLine(  109,  777 );
     plotLine(   94,  785 );
     plotLine(   82,  786 );
     plotLine(   64,  788 );
     plotPenUp();

     plotMove(  153,  798 );
     plotPenDown();
     plotLine(  142,  807 );
     plotLine(  131,  814 );
     plotLine(  121,  818 );
     plotLine(  108,  822 );
     plotLine(   87,  824 );
     plotPenUp();

     plotMove(  169,  796 );
     plotPenDown();
     plotLine(  162,  809 );
     plotLine(  149,  821 );
     plotLine(  140,  827 );
     plotLine(  130,  831 );
     plotPenUp();

     plotMove(  188,  820 );
     plotPenDown();
     plotLine(  182,  829 );
     plotLine(  169,  842 );
     plotLine(  153,  848 );
     plotPenUp();

     plotMove(  199,  824 );
     plotPenDown();
     plotLine(  192,  843 );
     plotLine(  184,  852 );
     plotLine(  173,  864 );
     plotLine(  159,  873 );
     plotLine(  141,  883 );
     plotPenUp();

     plotMove(  224,  830 );
     plotPenDown();
     plotLine(  217,  840 );
     plotLine(  207,  854 );
     plotLine(  195,  865 );
     plotLine(  178,  872 );
     plotPenUp();

     plotMove(  252,  823 );
     plotPenDown();
     plotLine(  248,  837 );
     plotLine(  243,  850 );
     plotLine(  237,  859 );
     plotLine(  226,  865 );
     plotPenUp();

     plotMove(  279,  842 );
     plotPenDown();
     plotLine(  277,  863 );
     plotLine(  276,  882 );
     plotLine(  281,  896 );
     plotLine(  289,  916 );
     plotLine(  291,  919 );
     plotPenUp();

     plotMove(  294,  844 );
     plotPenDown();
     plotLine(  294,  860 );
     plotLine(  294,  874 );
     plotLine(  299,  887 );
     plotLine(  309,  901 );
     plotPenUp();

     plotMove(  330,  844 );
     plotPenDown();
     plotLine(  336,  860 );
     plotLine(  344,  871 );
     plotLine(  355,  880 );
     plotPenUp();

     plotMove(  336,  841 );
     plotPenDown();
     plotLine(  336,  861 );
     plotLine(  341,  879 );
     plotLine(  348,  894 );
     plotLine(  365,  910 );
     plotPenUp();

     plotMove(  362,  825 );
     plotPenDown();
     plotLine(  366,  840 );
     plotLine(  372,  851 );
     plotLine(  385,  866 );
     plotLine(  389,  867 );
     plotPenUp();

     plotMove(  374,  833 );
     plotPenDown();
     plotLine(  385,  848 );
     plotLine(  394,  858 );
     plotLine(  407,  866 );
     plotLine(  424,  874 );
     plotPenUp();

     plotMove(  415,  816 );
     plotPenDown();
     plotLine(  426,  826 );
     plotLine(  434,  833 );
     plotLine(  445,  838 );
     plotLine(  457,  841 );
     plotLine(  467,  842 );
     plotPenUp();

     plotMove(  418,  809 );
     plotPenDown();
     plotLine(  431,  822 );
     plotLine(  444,  832 );
     plotLine(  456,  838 );
     plotLine(  475,  844 );
     plotLine(  489,  845 );
     plotPenUp();

     plotMove(  419,  803 );
     plotPenDown();
     plotLine(  434,  817 );
     plotLine(  447,  824 );
     plotLine(  458,  831 );
     plotLine(  470,  835 );
     plotPenUp();

     plotMove(  461,  779 );
     plotPenDown();
     plotLine(  475,  782 );
     plotLine(  491,  783 );
     plotPenUp();

     plotMove(  155,  638 );
     plotPenDown();
     plotLine(  173,  630 );
     plotLine(  190,  626 );
     plotLine(  204,  626 );
     plotLine(  222,  628 );
     plotLine(  238,  633 );
     plotLine(  254,  641 );
     plotLine(  263,  652 );
     plotLine(  272,  667 );
     plotLine(  274,  680 );
     plotLine(  272,  695 );
     plotLine(  263,  711 );
     plotLine(  247,  730 );
     plotLine(  230,  738 );
     plotLine(  210,  742 );
     plotLine(  192,  741 );
     plotLine(  172,  737 );
     plotLine(  158,  725 );
     plotLine(  148,  715 );
     plotLine(  144,  704 );
     plotLine(  140,  693 );
     plotLine(  138,  676 );
     plotLine(  140,  659 );
     plotLine(  144,  650 );
     plotLine(  155,  638 );
     plotPenUp();

     plotMove(  367,  648 );
     plotPenDown();
     plotLine(  393,  652 );
     plotLine(  403,  657 );
     plotLine(  418,  666 );
     plotLine(  427,  676 );
     plotLine(  433,  687 );
     plotLine(  437,  704 );
     plotLine(  434,  723 );
     plotLine(  425,  739 );
     plotLine(  411,  754 );
     plotLine(  395,  762 );
     plotLine(  369,  766 );
     plotLine(  353,  764 );
     plotLine(  334,  755 );
     plotLine(  325,  747 );
     plotLine(  313,  740 );
     plotLine(  307,  725 );
     plotLine(  303,  710 );
     plotLine(  303,  695 );
     plotLine(  306,  681 );
     plotLine(  313,  666 );
     plotLine(  327,  657 );
     plotLine(  342,  651 );
     plotLine(  353,  648 );
     plotLine(  368,  647 );
     plotPenUp();

     plotMove(  212,  659 );
     plotPenDown();
     plotLine(  216,  662 );
     plotLine(  219,  665 );
     plotLine(  219,  670 );
     plotLine(  218,  673 );
     plotLine(  214,  676 );
     plotLine(  208,  677 );
     plotLine(  203,  677 );
     plotLine(  201,  672 );
     plotLine(  200,  668 );
     plotLine(  200,  665 );
     plotLine(  202,  661 );
     plotLine(  203,  661 );
     plotLine(  207,  659 );
     plotLine(  210,  659 );
     plotLine(  212,  659 );
     plotPenUp();

     plotMove(  368,  682 );
     plotPenDown();
     plotLine(  372,  682 );
     plotLine(  376,  683 );
     plotLine(  379,  687 );
     plotLine(  380,  691 );
     plotLine(  380,  694 );
     plotLine(  380,  697 );
     plotLine(  375,  701 );
     plotLine(  370,  701 );
     plotLine(  366,  698 );
     plotLine(  364,  697 );
     plotLine(  362,  691 );
     plotLine(  362,  689 );
     plotLine(  364,  687 );
     plotLine(  364,  684 );
     plotLine(  366,  683 );
     plotLine(  369,  680 );
     plotPenUp();

     plotMove(  533,  416 );
     plotPenDown();
     plotLine(  533,  403 );
     plotLine(  532,  390 );
     plotLine(  529,  372 );
     plotLine(  525,  359 );
     plotPenUp();

}


///////////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
     // Initialize the plotter

     plotInit();

     plotMINION( 100, 200, 2.0 ;

     // Move back to home position

     plotMoveHome();
}

//---------------------------------------------------------------------------------------------------------
//   Plotter.Minion.c    ---   End of program
//---------------------------------------------------------------------------------------------------------
