#pragma config(Sensor, port3,  EndX,           sensorVexIQ_Touch)
#pragma config(Sensor, port4,  EndY,           sensorVexIQ_Touch)
#pragma config(Motor,  motor2,          MotorX,        tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor5,          MotorY,        tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          MotorPen,      tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

///////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                       //
//   VEX-IQ-Plotter v3     (C) Andreas Dreier / Germany        Please don't hesitate to send me a mail   //
//                             andreas@dreier-privat.de        when you found errors or when you have    //
//   Plotter.QUEY.c            21.11.2015                      ideas for improvements ;-)                //
//                                                                                                       //
///////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                       //
//   Necessary parts:                                                                                    //
//                                                                                                       //
//   1 x Super Kit       --> http://www.vexrobotics.com/vexiq/products/kits-bundles/super-kit-eu.html    //
//       P/N: 228-3670                                                                                   //
//                                                                                                       //
//   2 x Gear Add-On kit --> http://www.vexrobotics.com/vexiq/products/accessories/228-2532.html         //
//       P/N: 228-2532                                                                                   //
//                                                                                                       //
///////////////////////////////////////////////////////////////////////////////////////////////////////////


///////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                       //
//   Connections to the VEX-IQ brain:                                                                    //
//                                                                                                       //
//   Port   Type           Function                                                                      //
//   ----   ------------   -------------------------------------------------------------------           //
//    02    Motor          Movement x axis                                                               //
//    03    Touch sensor   Detecting right limitation of x axis                                          //
//    04    Touch sensor   Detecting bottom limitation of y axis                                         //
//    05    Motor          Movement y axis                                                               //
//    06    Motor          Movement pen up and down                                                      //
//                                                                                                       //
///////////////////////////////////////////////////////////////////////////////////////////////////////////

#include "plotBasics.inc"

///////////////////////////////////////////////////////////////////////////////////////////////////////////


float ms;
int   mx;
int   my;

///////////////////////////////////////////////////////////////////////////////////////////////////////////

void plotLine( int px, int py )
{
     plotLineTo( mx + ms * px, my + ms * py );
}

///////////////////////////////////////////////////////////////////////////////////////////////////////////

void plotMove( int px, int py )
{
     plotMoveTo( mx + ms * px, my + ms * py );
}

///////////////////////////////////////////////////////////////////////////////////////////////////////////

void plotQUEY( int x, int y, float scale = 1.0 )
{
     ms = scale;
     mx = x;
     my = y;

     plotMove(  591,  792 );
     plotPenDown();
     plotLine(  554,  811 );
     plotLine(  512,  825 );
     plotLine(  466,  834 );
     plotLine(  430,  834 );
     plotLine(  384,  834 );
     plotLine(  346,  828 );
     plotLine(  308,  819 );
     plotLine(  270,  806 );
     plotLine(  220,  783 );
     plotLine(  189,  766 );
     plotLine(  158,  741 );
     plotLine(  129,  711 );
     plotLine(  109,  681 );
     plotLine(   93,  647 );
     plotLine(   85,  619 );
     plotLine(   77,  576 );
     plotLine(   76,  550 );
     plotLine(   74,  527 );
     plotLine(   75,  505 );
     plotLine(   78,  467 );
     plotLine(   87,  421 );
     plotLine(  102,  371 );
     plotLine(  186,  380 );
     plotLine(  262,  393 );
     plotLine(  366,  413 );
     plotLine(  434,  431 );
     plotLine(  519,  457 );
     plotLine(  609,  484 );
     plotLine(  680,  510 );
     plotLine(  752,  540 );
     plotLine(  733,  601 );
     plotLine(  716,  642 );
     plotLine(  701,  673 );
     plotPenUp();

     plotMove(   99,  424 );
     plotPenDown();
     plotLine(  145,  421 );
     plotLine(  194,  423 );
     plotLine(  262,  428 );
     plotLine(  319,  439 );
     plotLine(  376,  452 );
     plotLine(  434,  469 );
     plotLine(  493,  490 );
     plotLine(  544,  511 );
     plotLine(  614,  551 );
     plotPenUp();

     plotMove(  540,  583 );
     plotPenDown();
     plotLine(  572,  594 );
     plotLine(  557,  647 );
     plotLine(  525,  636 );
     plotLine(  540,  581 );
     plotPenUp();

     plotMove(  126,  489 );
     plotPenDown();
     plotLine(  156,  493 );
     plotLine(  147,  547 );
     plotLine(  116,  543 );
     plotLine(  125,  489 );
     plotPenUp();

     plotMove(  287,  769 );
     plotPenDown();
     plotLine(  314,  773 );
     plotLine(  347,  783 );
     plotLine(  371,  796 );
     plotLine(  390,  809 );
     plotLine(  396,  816 );
     plotLine(  397,  820 );
     plotLine(  395,  824 );
     plotLine(  386,  828 );
     plotLine(  365,  830 );
     plotLine(  337,  826 );
     plotLine(  299,  816 );
     plotLine(  274,  805 );
     plotLine(  258,  794 );
     plotLine(  246,  783 );
     plotLine(  245,  777 );
     plotLine(  249,  772 );
     plotLine(  257,  769 );
     plotLine(  267,  769 );
     plotLine(  288,  771 );
     plotPenUp();

     plotMove(  412,  826 );
     plotPenDown();
     plotLine(  451,  824 );
     plotLine(  479,  822 );
     plotLine(  509,  813 );
     plotLine(  535,  801 );
     plotLine(  549,  793 );
     plotPenUp();

     plotMove(  682,  641 );
     plotPenDown();
     plotLine(  691,  619 );
     plotLine(  702,  591 );
     plotLine(  711,  565 );
     plotLine(  719,  541 );
     plotPenUp();

     plotMove(   96,  660 );
     plotPenDown();
     plotLine(   89,  674 );
     plotLine(   80,  681 );
     plotLine(   65,  685 );
     plotLine(   53,  683 );
     plotLine(   41,  671 );
     plotLine(   24,  649 );
     plotLine(   12,  621 );
     plotLine(    4,  590 );
     plotLine(    0,  554 );
     plotLine(    3,  524 );
     plotLine(    8,  500 );
     plotLine(   22,  481 );
     plotLine(   34,  472 );
     plotLine(   53,  476 );
     plotLine(   64,  484 );
     plotLine(   75,  494 );
     plotPenUp();

     plotMove(   71,  671 );
     plotPenDown();
     plotLine(   53,  668 );
     plotLine(   41,  653 );
     plotLine(   27,  626 );
     plotLine(   20,  601 );
     plotLine(   13,  574 );
     plotLine(   14,  553 );
     plotLine(   15,  528 );
     plotLine(   22,  507 );
     plotLine(   30,  492 );
     plotLine(   44,  486 );
     plotLine(   55,  488 );
     plotPenUp();

     plotMove(   85,  621 );
     plotPenDown();
     plotLine(   80,  621 );
     plotLine(   70,  614 );
     plotLine(   62,  604 );
     plotLine(   57,  583 );
     plotLine(   54,  564 );
     plotLine(   53,  544 );
     plotLine(   56,  531 );
     plotLine(   61,  524 );
     plotLine(   67,  524 );
     plotLine(   71,  525 );
     plotLine(   75,  528 );
     plotPenUp();

     plotMove(  728,  692 );
     plotPenDown();
     plotLine(  738,  694 );
     plotLine(  749,  700 );
     plotLine(  752,  713 );
     plotLine(  753,  727 );
     plotLine(  746,  749 );
     plotLine(  729,  778 );
     plotLine(  713,  794 );
     plotLine(  699,  809 );
     plotLine(  681,  822 );
     plotLine(  663,  832 );
     plotLine(  641,  842 );
     plotLine(  625,  846 );
     plotLine(  609,  846 );
     plotLine(  602,  841 );
     plotLine(  598,  833 );
     plotLine(  597,  826 );
     plotLine(  596,  817 );
     plotLine(  599,  799 );
     plotLine(  609,  781 );
     plotLine(  622,  759 );
     plotLine(  639,  740 );
     plotLine(  658,  723 );
     plotLine(  677,  709 );
     plotLine(  700,  697 );
     plotLine(  716,  691 );
     plotLine(  737,  695 );
     plotPenUp();

     plotMove(  740,  716 );
     plotPenDown();
     plotLine(  745,  725 );
     plotLine(  748,  739 );
     plotLine(  738,  760 );
     plotLine(  722,  785 );
     plotLine(  700,  807 );
     plotLine(  677,  824 );
     plotLine(  661,  833 );
     plotLine(  639,  837 );
     plotLine(  628,  836 );
     plotLine(  622,  833 );
     plotLine(  619,  825 );
     plotLine(  620,  816 );
     plotLine(  622,  804 );
     plotLine(  637,  779 );
     plotLine(  659,  749 );
     plotLine(  678,  733 );
     plotLine(  701,  718 );
     plotLine(  721,  711 );
     plotLine(  736,  711 );
     plotLine(  743,  717 );
     plotLine(  745,  724 );
     plotPenUp();

     plotMove(  605,  786 );
     plotPenDown();
     plotLine(  583,  793 );
     plotLine(  569,  793 );
     plotLine(  553,  794 );
     plotLine(  542,  786 );
     plotLine(  538,  774 );
     plotLine(  539,  758 );
     plotLine(  548,  737 );
     plotLine(  560,  713 );
     plotLine(  578,  694 );
     plotLine(  606,  670 );
     plotLine(  637,  651 );
     plotLine(  659,  644 );
     plotLine(  684,  640 );
     plotLine(  690,  645 );
     plotLine(  697,  652 );
     plotLine(  698,  663 );
     plotLine(  699,  680 );
     plotLine(  696,  698 );
     plotPenUp();

     plotMove(  608,  783 );
     plotPenDown();
     plotLine(  591,  772 );
     plotLine(  591,  762 );
     plotLine(  598,  745 );
     plotLine(  608,  727 );
     plotLine(  619,  715 );
     plotLine(  630,  705 );
     plotLine(  641,  696 );
     plotLine(  655,  691 );
     plotLine(  668,  688 );
     plotLine(  682,  707 );
     plotPenUp();

     plotMove(  601,  777 );
     plotPenDown();
     plotLine(  604,  757 );
     plotLine(  612,  743 );
     plotLine(  625,  726 );
     plotLine(  637,  713 );
     plotLine(  649,  706 );
     plotLine(  661,  699 );
     plotLine(  674,  700 );
     plotPenUp();

     plotMove(  365,  415 );
     plotPenDown();
     plotLine(  381,  372 );
     plotPenUp();

     plotMove(  432,  432 );
     plotPenDown();
     plotLine(  443,  394 );
     plotPenUp();

     plotMove(  480,  406 );
     plotPenDown();
     plotLine(  325,  350 );
     plotLine(  367,  222 );
     plotLine(  516,  230 );
     plotLine(  514,  246 );
     plotLine(  511,  253 );
     plotLine(  512,  264 );
     plotLine(  515,  273 );
     plotLine(  526,  275 );
     plotLine(  532,  281 );
     plotLine(  537,  287 );
     plotLine(  540,  333 );
     plotLine(  530,  329 );
     plotLine(  518,  329 );
     plotLine(  499,  334 );
     plotLine(  491,  345 );
     plotLine(  484,  359 );
     plotLine(  482,  373 );
     plotLine(  482,  385 );
     plotLine(  485,  400 );
     plotLine(  488,  410 );
     plotLine(  503,  418 );
     plotLine(  518,  419 );
     plotLine(  531,  415 );
     plotLine(  545,  406 );
     plotPenUp();

     plotMove(  451,  390 );
     plotPenDown();
     plotLine(  457,  369 );
     plotLine(  465,  338 );
     plotLine(  468,  307 );
     plotLine(  470,  275 );
     plotLine(  465,  250 );
     plotLine(  458,  228 );
     plotPenUp();

     plotMove(  381,  304 );
     plotPenDown();
     plotLine(  384,  287 );
     plotLine(  392,  277 );
     plotLine(  400,  274 );
     plotLine(  410,  273 );
     plotLine(  416,  277 );
     plotLine(  397,  297 );
     plotLine(  409,  309 );
     plotLine(  428,  290 );
     plotLine(  428,  309 );
     plotLine(  419,  324 );
     plotLine(  409,  330 );
     plotLine(  397,  327 );
     plotLine(  387,  320 );
     plotLine(  382,  308 );
     plotLine(  384,  289 );
     plotPenUp();

     plotMove(  418,  276 );
     plotPenDown();
     plotLine(  427,  264 );
     plotLine(  430,  261 );
     plotLine(  443,  271 );
     plotLine(  428,  290 );
     plotPenUp();

     plotMove(  438,  279 );
     plotPenDown();
     plotLine(  441,  287 );
     plotLine(  444,  297 );
     plotLine(  442,  312 );
     plotLine(  439,  325 );
     plotLine(  429,  338 );
     plotLine(  415,  344 );
     plotLine(  402,  347 );
     plotLine(  389,  345 );
     plotLine(  378,  334 );
     plotLine(  372,  323 );
     plotLine(  366,  308 );
     plotLine(  368,  290 );
     plotLine(  374,  273 );
     plotLine(  382,  263 );
     plotLine(  393,  258 );
     plotLine(  405,  256 );
     plotLine(  417,  260 );
     plotLine(  424,  266 );
     plotPenUp();

     plotMove(  508,  419 );
     plotPenDown();
     plotLine(  499,  411 );
     plotLine(  490,  401 );
     plotLine(  489,  390 );
     plotLine(  487,  375 );
     plotLine(  491,  359 );
     plotLine(  496,  347 );
     plotLine(  509,  338 );
     plotLine(  523,  331 );
     plotLine(  529,  330 );
     plotPenUp();

     plotMove(  516,  398 );
     plotPenDown();
     plotLine(  506,  388 );
     plotLine(  503,  377 );
     plotLine(  505,  364 );
     plotLine(  509,  353 );
     plotLine(  519,  341 );
     plotLine(  542,  336 );
     plotLine(  563,  335 );
     plotLine(  586,  335 );
     plotLine(  597,  323 );
     plotLine(  600,  314 );
     plotLine(  601,  303 );
     plotLine(  599,  295 );
     plotLine(  592,  290 );
     plotLine(  581,  287 );
     plotLine(  571,  284 );
     plotLine(  560,  287 );
     plotLine(  543,  289 );
     plotLine(  537,  289 );
     plotPenUp();

     plotMove(  516,  401 );
     plotPenDown();
     plotLine(  544,  400 );
     plotLine(  567,  398 );
     plotLine(  587,  392 );
     plotLine(  604,  384 );
     plotLine(  623,  371 );
     plotLine(  633,  358 );
     plotLine(  644,  343 );
     plotLine(  651,  321 );
     plotLine(  649,  296 );
     plotLine(  646,  281 );
     plotLine(  638,  260 );
     plotPenUp();

     plotMove(  598,  294 );
     plotPenDown();
     plotLine(  612,  284 );
     plotLine(  624,  276 );
     plotLine(  633,  264 );
     plotLine(  639,  252 );
     plotLine(  642,  238 );
     plotLine(  642,  234 );
     plotLine(  619,  215 );
     plotLine(  600,  208 );
     plotLine(  589,  207 );
     plotLine(  581,  233 );
     plotLine(  576,  251 );
     plotLine(  568,  265 );
     plotLine(  561,  279 );
     plotLine(  547,  287 );
     plotPenUp();

     plotMove(  604,  241 );
     plotPenDown();
     plotLine(  600,  237 );
     plotLine(  598,  229 );
     plotLine(  600,  224 );
     plotLine(  606,  219 );
     plotLine(  617,  218 );
     plotLine(  627,  224 );
     plotLine(  629,  234 );
     plotLine(  624,  243 );
     plotLine(  615,  248 );
     plotLine(  607,  243 );
     plotLine(  600,  238 );
     plotPenUp();

     plotMove(  640,  346 );
     plotPenDown();
     plotLine(  630,  348 );
     plotLine(  616,  350 );
     plotLine(  607,  343 );
     plotLine(  600,  334 );
     plotLine(  598,  324 );
     plotPenUp();

     plotMove(  578,  394 );
     plotPenDown();
     plotLine(  570,  390 );
     plotLine(  561,  379 );
     plotLine(  556,  367 );
     plotLine(  557,  352 );
     plotLine(  563,  342 );
     plotLine(  567,  335 );
     plotPenUp();

     plotMove(  512,  246 );
     plotPenDown();
     plotLine(  518,  246 );
     plotLine(  528,  244 );
     plotLine(  538,  244 );
     plotLine(  550,  245 );
     plotPenUp();

     plotMove(  526,  271 );
     plotPenDown();
     plotLine(  530,  271 );
     plotLine(  537,  271 );
     plotLine(  545,  274 );
     plotPenUp();

     plotMove(  525,  219 );
     plotPenDown();
     plotLine(  530,  219 );
     plotLine(  536,  219 );
     plotLine(  545,  219 );
     plotLine(  556,  219 );
     plotPenUp();

     plotMove(  589,  207 );
     plotPenDown();
     plotLine(  579,  202 );
     plotLine(  566,  200 );
     plotLine(  551,  200 );
     plotLine(  540,  200 );
     plotLine(  532,  202 );
     plotLine(  528,  206 );
     plotLine(  524,  214 );
     plotLine(  524,  219 );
     plotLine(  515,  230 );
     plotPenUp();

     plotMove(  367,  221 );
     plotPenDown();
     plotLine(  365,  208 );
     plotLine(  356,  195 );
     plotLine(  354,  178 );
     plotLine(  350,  165 );
     plotLine(  346,  147 );
     plotLine(  416,  113 );
     plotLine(  420,  121 );
     plotLine(  434,  125 );
     plotLine(  425,  145 );
     plotLine(  422,  168 );
     plotLine(  424,  183 );
     plotLine(  426,  195 );
     plotLine(  431,  214 );
     plotLine(  435,  223 );
     plotPenUp();

     plotMove(  362,  200 );
     plotPenDown();
     plotLine(  370,  202 );
     plotLine(  380,  203 );
     plotLine(  391,  199 );
     plotLine(  402,  194 );
     plotLine(  415,  188 );
     plotLine(  421,  179 );
     plotPenUp();

     plotMove(  352,  166 );
     plotPenDown();
     plotLine(  366,  168 );
     plotLine(  377,  168 );
     plotLine(  389,  165 );
     plotLine(  403,  158 );
     plotLine(  411,  152 );
     plotLine(  424,  145 );
     plotPenUp();

     plotMove(  450,  223 );
     plotPenDown();
     plotLine(  454,  211 );
     plotLine(  458,  197 );
     plotLine(  461,  179 );
     plotLine(  468,  161 );
     plotLine(  472,  143 );
     plotLine(  475,  127 );
     plotLine(  475,  114 );
     plotLine(  484,  111 );
     plotLine(  554,  130 );
     plotLine(  571,  137 );
     plotLine(  565,  147 );
     plotLine(  555,  157 );
     plotLine(  545,  171 );
     plotLine(  535,  190 );
     plotLine(  529,  202 );
     plotPenUp();

     plotMove(  465,  177 );
     plotPenDown();
     plotLine(  468,  183 );
     plotLine(  481,  191 );
     plotLine(  493,  197 );
     plotLine(  510,  201 );
     plotLine(  524,  203 );
     plotPenUp();

     plotMove(  476,  133 );
     plotPenDown();
     plotLine(  482,  141 );
     plotLine(  489,  146 );
     plotLine(  507,  152 );
     plotLine(  520,  158 );
     plotLine(  535,  160 );
     plotLine(  544,  161 );
     plotLine(  551,  160 );
     plotPenUp();

     plotMove(  346,  147 );
     plotPenDown();
     plotLine(  335,  138 );
     plotLine(  318,  128 );
     plotLine(  304,  113 );
     plotLine(  290,   99 );
     plotLine(  281,   76 );
     plotLine(  277,   58 );
     plotLine(  277,   42 );
     plotLine(  275,   28 );
     plotLine(  288,   21 );
     plotLine(  312,   18 );
     plotLine(  354,   18 );
     plotLine(  387,   20 );
     plotLine(  421,   21 );
     plotLine(  447,   24 );
     plotLine(  450,   35 );
     plotLine(  449,   59 );
     plotLine(  450,   78 );
     plotLine(  447,   98 );
     plotLine(  445,  114 );
     plotLine(  434,  127 );
     plotPenUp();

     plotMove(  413,   96 );
     plotPenDown();
     plotLine(  409,   91 );
     plotLine(  405,   84 );
     plotLine(  411,   78 );
     plotLine(  419,   79 );
     plotLine(  424,   87 );
     plotLine(  424,   95 );
     plotLine(  417,   99 );
     plotLine(  408,   96 );
     plotPenUp();

     plotMove(  277,   41 );
     plotPenDown();
     plotLine(  283,   34 );
     plotLine(  304,   31 );
     plotLine(  337,   28 );
     plotLine(  370,   28 );
     plotLine(  401,   30 );
     plotLine(  430,   32 );
     plotLine(  449,   34 );
     plotPenUp();

     plotMove(  475,  115 );
     plotPenDown();
     plotLine(  465,  102 );
     plotLine(  462,   84 );
     plotLine(  463,   52 );
     plotLine(  465,   23 );
     plotLine(  464,   13 );
     plotLine(  467,    8 );
     plotLine(  529,    0 );
     plotLine(  575,    0 );
     plotLine(  618,    2 );
     plotLine(  642,    9 );
     plotLine(  645,   20 );
     plotLine(  648,   41 );
     plotLine(  642,   65 );
     plotLine(  631,   86 );
     plotLine(  613,  111 );
     plotLine(  589,  126 );
     plotLine(  572,  136 );
     plotPenUp();

     plotMove(  466,   16 );
     plotPenDown();
     plotLine(  521,    9 );
     plotLine(  556,   12 );
     plotLine(  591,   14 );
     plotLine(  619,   15 );
     plotLine(  632,   19 );
     plotLine(  642,   24 );
     plotPenUp();

     plotMove(  474,   90 );
     plotPenDown();
     plotLine(  473,   79 );
     plotLine(  472,   70 );
     plotLine(  475,   65 );
     plotLine(  481,   57 );
     plotLine(  486,   64 );
     plotLine(  486,   74 );
     plotLine(  483,   86 );
     plotLine(  476,   91 );
     plotPenUp();

     plotMove(  375,  372 );
     plotPenDown();
     plotLine(  370,  377 );
     plotLine(  360,  380 );
     plotLine(  348,  379 );
     plotLine(  337,  370 );
     plotLine(  329,  361 );
     plotLine(  328,  353 );
     plotLine(  316,  343 );
     plotLine(  303,  334 );
     plotLine(  295,  320 );
     plotLine(  286,  309 );
     plotLine(  287,  293 );
     plotLine(  291,  274 );
     plotLine(  299,  256 );
     plotLine(  310,  243 );
     plotLine(  312,  241 );
     plotPenUp();

     plotMove(  335,  322 );
     plotPenDown();
     plotLine(  326,  314 );
     plotLine(  321,  303 );
     plotLine(  318,  289 );
     plotLine(  326,  274 );
     plotPenUp();

     plotMove(  284,  301 );
     plotPenDown();
     plotLine(  295,  305 );
     plotLine(  305,  307 );
     plotLine(  313,  304 );
     plotLine(  317,  297 );
     plotPenUp();

     plotMove(  311,  338 );
     plotPenDown();
     plotLine(  325,  335 );
     plotLine(  328,  329 );
     plotLine(  328,  320 );
     plotPenUp();

     plotMove(  309,  226 );
     plotPenDown();
     plotLine(  312,  241 );
     plotLine(  316,  256 );
     plotLine(  323,  266 );
     plotLine(  328,  275 );
     plotLine(  338,  277 );
     plotLine(  347,  273 );
     plotLine(  351,  265 );
     plotLine(  354,  255 );
     plotLine(  354,  246 );
     plotLine(  353,  235 );
     plotLine(  353,  226 );
     plotLine(  351,  219 );
     plotLine(  343,  219 );
     plotLine(  329,  219 );
     plotLine(  319,  223 );
     plotLine(  310,  232 );
     plotPenUp();

     plotMove(  322,  236 );
     plotPenDown();
     plotLine(  325,  241 );
     plotLine(  335,  242 );
     plotLine(  342,  238 );
     plotLine(  343,  231 );
     plotLine(  340,  224 );
     plotLine(  335,  222 );
     plotLine(  326,  223 );
     plotLine(  320,  229 );
     plotLine(  322,  236 );
     plotPenUp();

     plotMove(  351,  218 );
     plotPenDown();
     plotLine(  365,  214 );
     plotPenUp();

     plotMove(  555,  335 );
     plotPenDown();
     plotLine(  555,  305 );
     plotLine(  554,  288 );
     plotPenUp();

}


///////////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
     // Initialize the plotter

     plotInit();

     plotQUEY( 200, 200, 1.0 );

     // Move back to home position

     plotMoveHome();
}

//---------------------------------------------------------------------------------------------------------
//   Plotter.Minion.c    ---   End of program
//---------------------------------------------------------------------------------------------------------
