#pragma config(Sensor, port3,  EndX,           sensorVexIQ_Touch)
#pragma config(Sensor, port4,  EndY,           sensorVexIQ_Touch)
#pragma config(Motor,  motor2,          MotorX,        tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor5,          MotorY,        tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          MotorPen,      tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

///////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                       //
//   VEX-IQ-Plotter v3     (C) Andreas Dreier / Germany        Please don't hesitate to send me a mail   //
//                             andreas@dreier-privat.de        when you found errors or when you have    //
//   Plotter.R2D2.c            21.11.2015                      ideas for improvements ;-)                //
//                                                                                                       //
///////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                       //
//   Necessary parts:                                                                                    //
//                                                                                                       //
//   1 x Super Kit       --> http://www.vexrobotics.com/vexiq/products/kits-bundles/super-kit-eu.html    //
//       P/N: 228-3670                                                                                   //
//                                                                                                       //
//   2 x Gear Add-On kit --> http://www.vexrobotics.com/vexiq/products/accessories/228-2532.html         //
//       P/N: 228-2532                                                                                   //
//                                                                                                       //
///////////////////////////////////////////////////////////////////////////////////////////////////////////


///////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                       //
//   Connections to the VEX-IQ brain:                                                                    //
//                                                                                                       //
//   Port   Type           Function                                                                      //
//   ----   ------------   -------------------------------------------------------------------           //
//    02    Motor          Movement x axis                                                               //
//    03    Touch sensor   Detecting right limitation of x axis                                          //
//    04    Touch sensor   Detecting bottom limitation of y axis                                         //
//    05    Motor          Movement y axis                                                               //
//    06    Motor          Movement pen up and down                                                      //
//                                                                                                       //
///////////////////////////////////////////////////////////////////////////////////////////////////////////

#include "plotBasics.inc"

///////////////////////////////////////////////////////////////////////////////////////////////////////////


float ms;
int   mx;
int   my;

///////////////////////////////////////////////////////////////////////////////////////////////////////////

void plotLine( int px, int py )
{
     plotLineTo( mx + ms * px, my + ms * py );
}

///////////////////////////////////////////////////////////////////////////////////////////////////////////

void plotMove( int px, int py )
{
     plotMoveTo( mx + ms * px, my + ms * py );
}

///////////////////////////////////////////////////////////////////////////////////////////////////////////

void plotR2D2( int x, int y, float scale = 1.0 )
{
     ms = scale;
     mx = x;
     my = y;

     plotMove(   98,   20 );
     plotPenDown();
     plotLine(  199,    0 );
     plotLine(  212,   10 );
     plotLine(  273,   81 );
     plotLine(  276,   96 );
     plotLine(  224,  155 );
     plotLine(  201,  132 );
     plotLine(  185,  135 );
     plotLine(  161,   36 );
     plotLine(  142,   39 );
     plotLine(  165,  139 );
     plotLine(  147,  138 );
     plotLine(   89,   40 );
     plotLine(   99,   21 );
     plotPenUp();

     plotMove(   89,   40 );
     plotPenDown();
     plotLine(  211,   14 );
     plotLine(  203,  131 );
     plotPenUp();

     plotMove(  160,  108 );
     plotPenDown();
     plotLine(  176,  104 );
     plotPenUp();

     plotMove(  352,   92 );
     plotPenDown();
     plotLine(  360,   75 );
     plotLine(  469,   61 );
     plotLine(  475,   75 );
     plotLine(  520,  167 );
     plotLine(  487,  223 );
     plotLine(  464,  182 );
     plotLine(  450,  182 );
     plotLine(  438,   89 );
     plotLine(  421,   90 );
     plotLine(  421,  104 );
     plotLine(  408,  105 );
     plotLine(  391,  102 );
     plotLine(  376,   99 );
     plotLine(  364,   96 );
     plotLine(  350,   93 );
     plotLine(  337,   95 );
     plotLine(  336,  103 );
     plotLine(  341,  108 );
     plotLine(  353,  118 );
     plotLine(  359,  124 );
     plotLine(  362,  132 );
     plotLine(  368,  133 );
     plotLine(  370,  129 );
     plotLine(  369,  125 );
     plotLine(  363,  120 );
     plotLine(  348,  108 );
     plotLine(  349,  104 );
     plotLine(  362,  106 );
     plotLine(  380,  110 );
     plotLine(  397,  112 );
     plotLine(  411,  111 );
     plotLine(  424,  112 );
     plotLine(  430,  112 );
     plotLine(  436,  112 );
     plotLine(  438,  108 );
     plotLine(  436,  102 );
     plotLine(  431,   99 );
     plotLine(  424,  101 );
     plotLine(  421,  105 );
     plotPenUp();

     plotMove(  422,  113 );
     plotPenDown();
     plotLine(  424,  128 );
     plotLine(  416,  124 );
     plotLine(  405,  120 );
     plotLine(  394,  117 );
     plotLine(  385,  114 );
     plotLine(  377,  111 );
     plotLine(  361,  108 );
     plotLine(  370,  115 );
     plotLine(  377,  122 );
     plotLine(  380,  129 );
     plotLine(  387,  133 );
     plotLine(  390,  127 );
     plotLine(  387,  123 );
     plotLine(  380,  118 );
     plotLine(  400,  127 );
     plotLine(  413,  131 );
     plotLine(  424,  137 );
     plotLine(  429,  141 );
     plotLine(  436,  140 );
     plotLine(  438,  137 );
     plotLine(  435,  132 );
     plotLine(  429,  130 );
     plotLine(  424,  131 );
     plotPenUp();

     plotMove(  426,  141 );
     plotPenDown();
     plotLine(  428,  152 );
     plotLine(  445,  153 );
     plotPenUp();

     plotMove(  463,  182 );
     plotPenDown();
     plotLine(  475,   77 );
     plotLine(  353,   92 );
     plotPenUp();

     plotMove(  356,  126 );
     plotPenDown();
     plotLine(  351,  133 );
     plotLine(  352,  143 );
     plotLine(  401,  138 );
     plotLine(  399,  129 );
     plotPenUp();

     plotMove(  401,  139 );
     plotPenDown();
     plotLine(  404,  168 );
     plotLine(  406,  189 );
     plotLine(  406,  207 );
     plotLine(  404,  221 );
     plotLine(  403,  225 );
     plotLine(  362,  227 );
     plotLine(  359,  213 );
     plotLine(  355,  211 );
     plotLine(  354,  175 );
     plotLine(  352,  143 );
     plotPenUp();

     plotMove(  356,  214 );
     plotPenDown();
     plotLine(  347,  210 );
     plotLine(  325,  205 );
     plotLine(  301,  205 );
     plotLine(  283,  205 );
     plotLine(  263,  206 );
     plotLine(  231,  210 );
     plotLine(  206,  213 );
     plotLine(  179,  217 );
     plotLine(  147,  222 );
     plotLine(  120,  228 );
     plotLine(   97,  231 );
     plotLine(   74,  237 );
     plotLine(   57,  242 );
     plotLine(   45,  248 );
     plotLine(   37,  255 );
     plotLine(   79,  608 );
     plotLine(   97,  608 );
     plotLine(  129,  606 );
     plotLine(  161,  602 );
     plotLine(  194,  598 );
     plotLine(  225,  592 );
     plotLine(  263,  588 );
     plotLine(  294,  583 );
     plotLine(  324,  578 );
     plotLine(  355,  574 );
     plotLine(  379,  570 );
     plotLine(  401,  568 );
     plotLine(  405,  568 );
     plotLine(  456,  565 );
     plotLine(  466,  552 );
     plotLine(  468,  536 );
     plotLine(  469,  514 );
     plotLine(  471,  480 );
     plotLine(  473,  480 );
     plotLine(  473,  471 );
     plotLine(  472,  454 );
     plotLine(  466,  425 );
     plotLine(  475,  415 );
     plotLine(  471,  408 );
     plotLine(  478,  406 );
     plotLine(  475,  393 );
     plotLine(  465,  385 );
     plotLine(  470,  317 );
     plotLine(  474,  308 );
     plotLine(  477,  294 );
     plotLine(  476,  285 );
     plotLine(  478,  275 );
     plotLine(  489,  269 );
     plotLine(  490,  263 );
     plotLine(  486,  251 );
     plotLine(  482,  247 );
     plotLine(  473,  218 );
     plotLine(  466,  184 );
     plotPenUp();

     plotMove(  485,  222 );
     plotPenDown();
     plotLine(  476,  225 );
     plotPenUp();

     plotMove(  362,  227 );
     plotPenDown();
     plotLine(  386,  394 );
     plotLine(  390,  376 );
     plotLine(  437,  371 );
     plotLine(  435,  400 );
     plotLine(  432,  445 );
     plotLine(  433,  483 );
     plotLine(  437,  517 );
     plotLine(  443,  541 );
     plotLine(  448,  555 );
     plotLine(  453,  562 );
     plotLine(  458,  562 );
     plotPenUp();

     plotMove(  436,  566 );
     plotPenDown();
     plotLine(  431,  560 );
     plotLine(  427,  553 );
     plotLine(  423,  542 );
     plotLine(  420,  528 );
     plotLine(  418,  512 );
     plotLine(  415,  495 );
     plotLine(  413,  473 );
     plotLine(  414,  443 );
     plotLine(  417,  413 );
     plotLine(  420,  372 );
     plotPenUp();

     plotMove(  386,  396 );
     plotPenDown();
     plotLine(  383,  432 );
     plotLine(  381,  468 );
     plotLine(  383,  493 );
     plotLine(  386,  516 );
     plotLine(  388,  534 );
     plotLine(  393,  547 );
     plotLine(  399,  559 );
     plotLine(  408,  566 );
     plotPenUp();

     plotMove(  391,  549 );
     plotPenDown();
     plotLine(  381,  541 );
     plotLine(  375,  528 );
     plotLine(  369,  513 );
     plotLine(  366,  492 );
     plotLine(  366,  471 );
     plotLine(  370,  451 );
     plotLine(  379,  437 );
     plotLine(  381,  431 );
     plotPenUp();

     plotMove(  267,  212 );
     plotPenDown();
     plotLine(  280,  302 );
     plotLine(  344,  299 );
     plotLine(  333,  213 );
     plotLine(  297,  212 );
     plotLine(  268,  214 );
     plotPenUp();

     plotMove(  256,  216 );
     plotPenDown();
     plotLine(  261,  272 );
     plotLine(  191,  280 );
     plotLine(  183,  225 );
     plotLine(  255,  216 );
     plotPenUp();

     plotMove(  116,  236 );
     plotPenDown();
     plotLine(  169,  228 );
     plotLine(  175,  282 );
     plotLine(  122,  291 );
     plotLine(  115,  238 );
     plotPenUp();

     plotMove(  101,  240 );
     plotPenDown();
     plotLine(  108,  293 );
     plotLine(   86,  297 );
     plotLine(   78,  245 );
     plotLine(   99,  239 );
     plotPenUp();

     plotMove(   70,  247 );
     plotPenDown();
     plotLine(   78,  301 );
     plotLine(   68,  303 );
     plotLine(   60,  250 );
     plotLine(   70,  248 );
     plotPenUp();

     plotMove(   62,  305 );
     plotPenDown();
     plotLine(   56,  307 );
     plotLine(   49,  253 );
     plotLine(   55,  252 );
     plotLine(   61,  306 );
     plotPenUp();

     plotMove(   79,  610 );
     plotPenDown();
     plotLine(   83,  629 );
     plotLine(   90,  663 );
     plotLine(  101,  694 );
     plotLine(  118,  724 );
     plotLine(  135,  743 );
     plotLine(  155,  763 );
     plotLine(  175,  781 );
     plotLine(  198,  791 );
     plotLine(  214,  797 );
     plotLine(  228,  803 );
     plotLine(  253,  805 );
     plotLine(  273,  801 );
     plotLine(  292,  798 );
     plotLine(  308,  791 );
     plotLine(  327,  779 );
     plotLine(  348,  764 );
     plotLine(  369,  743 );
     plotLine(  385,  721 );
     plotLine(  399,  696 );
     plotLine(  408,  670 );
     plotLine(  411,  646 );
     plotLine(  411,  625 );
     plotLine(  411,  605 );
     plotLine(  410,  582 );
     plotLine(  408,  567 );
     plotPenUp();

     plotMove(  410,  583 );
     plotPenDown();
     plotLine(  389,  591 );
     plotLine(  366,  595 );
     plotLine(  333,  600 );
     plotLine(  293,  607 );
     plotLine(  249,  614 );
     plotLine(  204,  621 );
     plotLine(  157,  626 );
     plotLine(  128,  630 );
     plotLine(  100,  630 );
     plotLine(   82,  631 );
     plotPenUp();

     plotMove(   86,  646 );
     plotPenDown();
     plotLine(  100,  646 );
     plotLine(  128,  644 );
     plotLine(  158,  640 );
     plotLine(  189,  637 );
     plotLine(  222,  633 );
     plotLine(  258,  628 );
     plotLine(  300,  623 );
     plotLine(  330,  617 );
     plotLine(  365,  612 );
     plotLine(  389,  606 );
     plotLine(  411,  600 );
     plotPenUp();

     plotMove(  408,  663 );
     plotPenDown();
     plotLine(  386,  669 );
     plotLine(  362,  674 );
     plotLine(  334,  679 );
     plotLine(  332,  623 );
     plotLine(  345,  619 );
     plotLine(  369,  615 );
     plotLine(  386,  612 );
     plotLine(  400,  609 );
     plotLine(  409,  605 );
     plotPenUp();

     plotMove(  320,  623 );
     plotPenDown();
     plotLine(  323,  652 );
     plotLine(  324,  682 );
     plotLine(  313,  682 );
     plotLine(  313,  658 );
     plotLine(  313,  638 );
     plotLine(  310,  625 );
     plotLine(  320,  623 );
     plotPenUp();

     plotMove(  304,  628 );
     plotPenDown();
     plotLine(  307,  649 );
     plotLine(  307,  667 );
     plotLine(  307,  684 );
     plotLine(  272,  690 );
     plotLine(  271,  666 );
     plotLine(  270,  649 );
     plotLine(  268,  632 );
     plotPenUp();

     plotMove(  273,  640 );
     plotPenDown();
     plotLine(  300,  634 );
     plotLine(  302,  655 );
     plotLine(  276,  657 );
     plotLine(  274,  641 );
     plotPenUp();

     plotMove(  276,  664 );
     plotPenDown();
     plotLine(  302,  661 );
     plotLine(  302,  680 );
     plotLine(  276,  685 );
     plotLine(  276,  665 );
     plotPenUp();

     plotMove(  174,  643 );
     plotPenDown();
     plotLine(  198,  640 );
     plotLine(  222,  638 );
     plotLine(  238,  635 );
     plotLine(  243,  676 );
     plotLine(  180,  683 );
     plotLine(  172,  646 );
     plotPenUp();

     plotMove(  185,  656 );
     plotPenDown();
     plotLine(  186,  648 );
     plotLine(  191,  646 );
     plotLine(  196,  644 );
     plotLine(  203,  644 );
     plotLine(  209,  648 );
     plotLine(  213,  655 );
     plotLine(  213,  662 );
     plotLine(  206,  669 );
     plotLine(  197,  672 );
     plotLine(  189,  670 );
     plotLine(  184,  661 );
     plotLine(  184,  655 );
     plotPenUp();

     plotMove(  245,  635 );
     plotPenDown();
     plotLine(  258,  634 );
     plotLine(  262,  649 );
     plotLine(  266,  672 );
     plotLine(  249,  676 );
     plotLine(  244,  637 );
     plotPenUp();

     plotMove(  269,  691 );
     plotPenDown();
     plotLine(  267,  759 );
     plotLine(  236,  765 );
     plotLine(  209,  768 );
     plotLine(  193,  769 );
     plotLine(  191,  763 );
     plotLine(  184,  762 );
     plotLine(  169,  721 );
     plotLine(  175,  721 );
     plotLine(  175,  718 );
     plotLine(  164,  718 );
     plotLine(  161,  704 );
     plotLine(  166,  700 );
     plotLine(  187,  702 );
     plotLine(  208,  702 );
     plotLine(  228,  699 );
     plotLine(  243,  696 );
     plotLine(  250,  693 );
     plotLine(  270,  691 );
     plotLine(  270,  681 );
     plotLine(  250,  679 );
     plotLine(  221,  683 );
     plotLine(  193,  686 );
     plotLine(  178,  687 );
     plotLine(  165,  701 );
     plotPenUp();

     plotMove(  206,  715 );
     plotPenDown();
     plotLine(  211,  711 );
     plotLine(  220,  710 );
     plotLine(  230,  710 );
     plotLine(  238,  712 );
     plotLine(  250,  719 );
     plotLine(  254,  730 );
     plotLine(  254,  744 );
     plotLine(  245,  755 );
     plotLine(  229,  758 );
     plotLine(  215,  756 );
     plotLine(  208,  749 );
     plotLine(  202,  741 );
     plotLine(  200,  731 );
     plotLine(  202,  723 );
     plotLine(  205,  717 );
     plotPenUp();

     plotMove(  203,  290 );
     plotPenDown();
     plotLine(  239,  284 );
     plotLine(  243,  306 );
     plotLine(  206,  312 );
     plotLine(  203,  290 );
     plotPenUp();

     plotMove(  118,  302 );
     plotPenDown();
     plotLine(  182,  291 );
     plotLine(  185,  314 );
     plotLine(  122,  324 );
     plotLine(  118,  302 );
     plotPenUp();

     plotMove(  101,  307 );
     plotPenDown();
     plotLine(  105,  327 );
     plotLine(   65,  337 );
     plotLine(   62,  317 );
     plotLine(  101,  308 );
     plotPenUp();

     plotMove(   45,  323 );
     plotPenDown();
     plotLine(   56,  320 );
     plotLine(   58,  340 );
     plotLine(   48,  342 );
     plotPenUp();

     plotMove(   65,  348 );
     plotPenDown();
     plotLine(  113,  339 );
     plotLine(  132,  479 );
     plotLine(   83,  487 );
     plotLine(   65,  349 );
     plotPenUp();

     plotMove(   48,  352 );
     plotPenDown();
     plotLine(   61,  350 );
     plotLine(   91,  588 );
     plotLine(   79,  589 );
     plotPenUp();

     plotMove(  102,  608 );
     plotPenDown();
     plotLine(   86,  498 );
     plotLine(  134,  489 );
     plotLine(  168,  485 );
     plotLine(  200,  480 );
     plotLine(  237,  476 );
     plotLine(  268,  470 );
     plotLine(  289,  468 );
     plotLine(  306,  581 );
     plotPenUp();

     plotMove(   92,  542 );
     plotPenDown();
     plotLine(  126,  536 );
     plotLine(  167,  531 );
     plotLine(  211,  524 );
     plotLine(  244,  519 );
     plotLine(  276,  516 );
     plotLine(  295,  516 );
     plotPenUp();

     plotMove(  101,  556 );
     plotPenDown();
     plotLine(  104,  572 );
     plotLine(  114,  571 );
     plotLine(  130,  575 );
     plotLine(  154,  571 );
     plotLine(  186,  566 );
     plotLine(  206,  564 );
     plotLine(  205,  558 );
     plotLine(  244,  558 );
     plotLine(  282,  550 );
     plotLine(  280,  530 );
     plotLine(  242,  532 );
     plotLine(  204,  544 );
     plotLine(  202,  534 );
     plotLine(  162,  540 );
     plotLine(  134,  544 );
     plotLine(  124,  547 );
     plotLine(  110,  555 );
     plotLine(  101,  556 );
     plotPenUp();

     plotMove(  245,  556 );
     plotPenDown();
     plotLine(  242,  534 );
     plotPenUp();

     plotMove(   97,  510 );
     plotPenDown();
     plotLine(  120,  503 );
     plotLine(  128,  503 );
     plotLine(  153,  505 );
     plotLine(  152,  495 );
     plotLine(  196,  489 );
     plotLine(  235,  483 );
     plotLine(  251,  487 );
     plotLine(  275,  484 );
     plotLine(  276,  503 );
     plotLine(  249,  506 );
     plotLine(  236,  513 );
     plotLine(  200,  516 );
     plotLine(  154,  523 );
     plotLine(  153,  516 );
     plotLine(  132,  524 );
     plotLine(  122,  526 );
     plotLine(   99,  528 );
     plotLine(   97,  510 );
     plotPenUp();

     plotMove(  197,  323 );
     plotPenDown();
     plotLine(  232,  319 );
     plotLine(  244,  405 );
     plotLine(  209,  410 );
     plotLine(  197,  324 );
     plotPenUp();

     plotMove(  211,  419 );
     plotPenDown();
     plotLine(  283,  411 );
     plotLine(  289,  457 );
     plotLine(  218,  467 );
     plotLine(  211,  420 );
     plotPenUp();

     plotMove(  122,  337 );
     plotPenDown();
     plotLine(  187,  327 );
     plotLine(  207,  468 );
     plotLine(  141,  478 );
     plotLine(  122,  337 );
     plotPenUp();

     plotMove(  147,  340 );
     plotPenDown();
     plotLine(  163,  336 );
     plotLine(  172,  339 );
     plotLine(  177,  347 );
     plotLine(  181,  362 );
     plotLine(  182,  376 );
     plotLine(  178,  389 );
     plotLine(  163,  394 );
     plotLine(  151,  396 );
     plotLine(  141,  391 );
     plotLine(  136,  382 );
     plotLine(  134,  368 );
     plotLine(  133,  355 );
     plotLine(  136,  348 );
     plotLine(  141,  344 );
     plotLine(  147,  341 );
     plotPenUp();

     plotMove(  153,  409 );
     plotPenDown();
     plotLine(  171,  406 );
     plotLine(  181,  407 );
     plotLine(  188,  415 );
     plotLine(  190,  427 );
     plotLine(  193,  441 );
     plotLine(  191,  451 );
     plotLine(  183,  462 );
     plotLine(  171,  465 );
     plotLine(  158,  464 );
     plotLine(  148,  459 );
     plotLine(  143,  449 );
     plotLine(  141,  434 );
     plotLine(  141,  423 );
     plotLine(  145,  414 );
     plotLine(  154,  409 );
     plotPenUp();

     plotMove(  126,  249 );
     plotPenDown();
     plotLine(  134,  239 );
     plotLine(  146,  235 );
     plotLine(  158,  236 );
     plotLine(  166,  244 );
     plotLine(  170,  258 );
     plotLine(  169,  270 );
     plotLine(  162,  278 );
     plotLine(  150,  285 );
     plotLine(  137,  285 );
     plotLine(  129,  277 );
     plotLine(  124,  267 );
     plotLine(  124,  257 );
     plotLine(  127,  249 );
     plotPenUp();

     plotMove(  226,  261 );
     plotPenDown();
     plotLine(  221,  228 );
     plotLine(  246,  225 );
     plotLine(  249,  260 );
     plotLine(  225,  262 );
     plotPenUp();

     plotMove(  282,  311 );
     plotPenDown();
     plotLine(  315,  559 );
     plotLine(  362,  553 );
     plotLine(  329,  308 );
     plotLine(  284,  314 );
     plotPenUp();

     plotMove(   76,  607 );
     plotPenDown();
     plotLine(   36,  613 );
     plotLine(   28,  609 );
     plotLine(   20,  601 );
     plotLine(   12,  583 );
     plotLine(    8,  566 );
     plotLine(    3,  546 );
     plotLine(    3,  526 );
     plotLine(    5,  507 );
     plotLine(   17,  432 );
     plotLine(   56,  426 );
     plotPenUp();

     plotMove(   30,  431 );
     plotPenDown();
     plotLine(   18,  509 );
     plotLine(   18,  527 );
     plotLine(   19,  549 );
     plotLine(   25,  568 );
     plotLine(   30,  585 );
     plotLine(   38,  598 );
     plotLine(   49,  609 );
     plotPenUp();

     plotMove(   76,  607 );
     plotPenDown();
     plotLine(   65,  596 );
     plotLine(   59,  580 );
     plotLine(   53,  562 );
     plotLine(   49,  542 );
     plotLine(   48,  524 );
     plotLine(   49,  505 );
     plotLine(   59,  446 );
     plotPenUp();

     plotMove(   76,  592 );
     plotPenDown();
     plotLine(   69,  585 );
     plotLine(   63,  573 );
     plotLine(   57,  555 );
     plotLine(   56,  537 );
     plotLine(   55,  521 );
     plotLine(   57,  506 );
     plotLine(   59,  498 );
     plotLine(   64,  490 );
     plotPenUp();

     plotMove(   47,  243 );
     plotPenDown();
     plotLine(   36,  215 );
     plotLine(    0,  151 );
     plotLine(  105,  127 );
     plotLine(  106,  115 );
     plotLine(    8,  132 );
     plotLine(    1,  150 );
     plotPenUp();

     plotMove(   52,  244 );
     plotPenDown();
     plotLine(   73,  198 );
     plotLine(  134,  185 );
     plotLine(  173,  179 );
     plotLine(  229,  170 );
     plotLine(  262,  166 );
     plotLine(  309,  179 );
     plotLine(  328,  206 );
     plotPenUp();

     plotMove(  283,  204 );
     plotPenDown();
     plotLine(  260,  167 );
     plotPenUp();

     plotMove(  246,  208 );
     plotPenDown();
     plotLine(  230,  172 );
     plotPenUp();

     plotMove(  168,  218 );
     plotPenDown();
     plotLine(  172,  181 );
     plotPenUp();

     plotMove(  127,  226 );
     plotPenDown();
     plotLine(  134,  187 );
     plotPenUp();

     plotMove(   74,  237 );
     plotPenDown();
     plotLine(   93,  195 );
     plotPenUp();

     plotMove(  154,  176 );
     plotPenDown();
     plotLine(  198,  168 );
     plotLine(  199,  158 );
     plotLine(  184,  157 );
     plotLine(  188,  140 );
     plotPenUp();

     plotMove(  183,  129 );
     plotPenDown();
     plotLine(  175,  130 );
     plotLine(  170,  160 );
     plotLine(  155,  165 );
     plotLine(  153,  175 );
     plotPenUp();

     plotMove(  198,  159 );
     plotPenDown();
     plotLine(  224,  162 );
     plotLine(  225,  169 );
     plotPenUp();

     plotMove(  153,  177 );
     plotPenDown();
     plotLine(  160,  181 );
     plotPenUp();

     plotMove(  148,  141 );
     plotPenDown();
     plotLine(  169,  160 );
     plotPenUp();

     plotMove(  123,  169 );
     plotPenDown();
     plotLine(  118,  167 );
     plotLine(  118,  160 );
     plotLine(  119,  151 );
     plotLine(  119,  144 );
     plotLine(  113,  145 );
     plotLine(   99,  153 );
     plotLine(   88,  160 );
     plotLine(   70,  167 );
     plotLine(   55,  172 );
     plotLine(   42,  171 );
     plotLine(   38,  171 );
     plotLine(   39,  163 );
     plotLine(   47,  161 );
     plotLine(   55,  165 );
     plotLine(   66,  162 );
     plotLine(   81,  155 );
     plotLine(   95,  146 );
     plotLine(  105,  141 );
     plotLine(  116,  136 );
     plotLine(  120,  136 );
     plotLine(  124,  142 );
     plotLine(  123,  151 );
     plotLine(  126,  162 );
     plotLine(  128,  167 );
     plotLine(  123,  171 );
     plotLine(  119,  168 );
     plotPenUp();

     plotMove(  106,  116 );
     plotPenDown();
     plotLine(  154,  165 );
     plotPenUp();

     plotMove(  106,  128 );
     plotPenDown();
     plotLine(  114,  136 );
     plotPenUp();

     plotMove(  123,  146 );
     plotPenDown();
     plotLine(  152,  175 );
     plotPenUp();

     plotMove(  106,  172 );
     plotPenDown();
     plotLine(  101,  169 );
     plotLine(   94,  167 );
     plotLine(   87,  178 );
     plotLine(   73,  188 );
     plotLine(   64,  196 );
     plotLine(   54,  199 );
     plotLine(   45,  199 );
     plotLine(   46,  191 );
     plotLine(   49,  187 );
     plotLine(   60,  190 );
     plotLine(   71,  182 );
     plotLine(   81,  174 );
     plotLine(   87,  165 );
     plotLine(   96,  159 );
     plotLine(  106,  158 );
     plotLine(  110,  163 );
     plotLine(  108,  171 );
     plotPenUp();

     plotMove(   86,  193 );
     plotPenDown();
     plotLine(   83,  183 );
     plotPenUp();

     plotMove(   79,  175 );
     plotPenDown();
     plotLine(   75,  165 );
     plotPenUp();

     plotMove(   75,  156 );
     plotPenDown();
     plotLine(   75,  151 );
     plotLine(   77,  144 );
     plotLine(   83,  136 );
     plotLine(   95,  132 );
     plotLine(  105,  128 );
     plotPenUp();

     plotMove(   52,  210 );
     plotPenDown();
     plotLine(   47,  201 );
     plotLine(   43,  190 );
     plotLine(   39,  172 );
     plotLine(   33,  153 );
     plotLine(   47,  150 );
     plotLine(   52,  162 );
     plotPenUp();

     plotMove(   57,  173 );
     plotPenDown();
     plotLine(   61,  187 );
     plotPenUp();

     plotMove(   66,  197 );
     plotPenDown();
     plotLine(   68,  209 );
     plotLine(   53,  210 );
     plotLine(   59,  229 );
     plotPenUp();

     plotMove(  384,  417 );
     plotPenDown();
     plotLine(  367,  417 );
     plotLine(  353,  308 );
     plotLine(  373,  307 );
     plotPenUp();

     plotMove(  170,  682 );
     plotPenDown();
     plotLine(  166,  690 );
     plotLine(  155,  694 );
     plotLine(  142,  693 );
     plotLine(  135,  690 );
     plotLine(  127,  688 );
     plotLine(  123,  680 );
     plotLine(  122,  675 );
     plotLine(  124,  668 );
     plotLine(  130,  662 );
     plotLine(  136,  666 );
     plotLine(  140,  672 );
     plotLine(  140,  681 );
     plotLine(  138,  688 );
     plotLine(  133,  690 );
     plotPenUp();

     plotMove(  130,  663 );
     plotPenDown();
     plotLine(  137,  657 );
     plotLine(  144,  652 );
     plotLine(  156,  655 );
     plotLine(  164,  664 );
     plotLine(  167,  672 );
     plotLine(  169,  681 );
     plotPenUp();

     plotMove(  116,  705 );
     plotPenDown();
     plotLine(   94,  649 );
     plotLine(  116,  648 );
     plotLine(  122,  667 );
     plotPenUp();

     plotMove(  128,  691 );
     plotPenDown();
     plotLine(  133,  703 );
     plotLine(  115,  703 );
     plotPenUp();

     plotMove(  397,  375 );
     plotPenDown();
     plotLine(  408,  286 );
     plotLine(  398,  287 );
     plotLine(  390,  283 );
     plotLine(  385,  278 );
     plotLine(  367,  257 );
     plotLine(  367,  251 );
     plotLine(  365,  243 );
     plotLine(  375,  245 );
     plotLine(  387,  241 );
     plotLine(  395,  234 );
     plotLine(  402,  226 );
     plotPenUp();

     plotMove(  365,  251 );
     plotPenDown();
     plotLine(  373,  250 );
     plotLine(  386,  251 );
     plotLine(  406,  280 );
     plotPenUp();

     plotMove(  407,  284 );
     plotPenDown();
     plotLine(  408,  272 );
     plotLine(  401,  266 );
     plotLine(  437,  260 );
     plotLine(  452,  266 );
     plotLine(  467,  276 );
     plotLine(  475,  285 );
     plotPenUp();

     plotMove(  410,  273 );
     plotPenDown();
     plotLine(  440,  271 );
     plotLine(  432,  365 );
     plotLine(  400,  370 );
     plotPenUp();

     plotMove(  406,  307 );
     plotPenDown();
     plotLine(  437,  305 );
     plotPenUp();

     plotMove(  440,  277 );
     plotPenDown();
     plotLine(  456,  274 );
     plotLine(  448,  368 );
     plotLine(  442,  436 );
     plotLine(  447,  457 );
     plotLine(  442,  471 );
     plotLine(  443,  485 );
     plotLine(  445,  498 );
     plotLine(  449,  511 );
     plotLine(  450,  518 );
     plotLine(  453,  522 );
     plotLine(  458,  518 );
     plotLine(  459,  513 );
     plotLine(  460,  491 );
     plotLine(  462,  481 );
     plotLine(  470,  480 );
     plotPenUp();

     plotMove(  438,  311 );
     plotPenDown();
     plotLine(  453,  309 );
     plotLine(  462,  318 );
     plotPenUp();

     plotMove(  457,  277 );
     plotPenDown();
     plotLine(  465,  287 );
     plotLine(  477,  291 );
     plotPenUp();

     plotMove(  464,  288 );
     plotPenDown();
     plotLine(  457,  380 );
     plotLine(  449,  387 );
     plotPenUp();

     plotMove(  449,  404 );
     plotPenDown();
     plotLine(  467,  424 );
     plotLine(  459,  418 );
     plotLine(  459,  445 );
     plotLine(  446,  449 );
     plotLine(  458,  446 );
     plotLine(  462,  452 );
     plotLine(  467,  463 );
     plotLine(  470,  471 );
     plotLine(  470,  479 );
     plotPenUp();

     plotMove(   38,  430 );
     plotPenDown();
     plotLine(   49,  366 );
     plotPenUp();

     plotMove(   40,  421 );
     plotPenDown();
     plotLine(   55,  419 );
     plotPenUp();

     plotMove(   46,  427 );
     plotPenDown();
     plotLine(   53,  398 );
     plotPenUp();

     plotMove(  174,  779 );
     plotPenDown();
     plotLine(  210,  779 );
     plotLine(  226,  778 );
     plotLine(  242,  777 );
     plotLine(  256,  798 );
     plotLine(  238,  800 );
     plotLine(  221,  801 );
     plotPenUp();

     plotMove(  308,  792 );
     plotPenDown();
     plotLine(  290,  793 );
     plotLine(  264,  797 );
     plotLine(  251,  776 );
     plotLine(  283,  771 );
     plotLine(  309,  767 );
     plotLine(  329,  763 );
     plotLine(  342,  758 );
     plotLine(  324,  778 );
     plotLine(  305,  792 );
     plotPenUp();

     plotMove(  105,  606 );
     plotPenDown();
     plotLine(  106,  590 );
     plotLine(  159,  583 );
     plotLine(  199,  577 );
     plotLine(  235,  572 );
     plotLine(  269,  568 );
     plotLine(  285,  564 );
     plotLine(  290,  584 );
     plotPenUp();

}


///////////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
     // Initialize the plotter

     plotInit();

     plotR2D2( 200, 200, 2.0 );

     // Move back to home position

     plotMoveHome();
}

//---------------------------------------------------------------------------------------------------------
//   Plotter.Minion.c    ---   End of program
//---------------------------------------------------------------------------------------------------------
