#pragma config(Sensor, port3,  EndX,           sensorVexIQ_Touch)
#pragma config(Sensor, port4,  EndY,           sensorVexIQ_Touch)
#pragma config(Motor,  motor2,          MotorX,        tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor5,          MotorY,        tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          MotorPen,      tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

///////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                       //
//   VEX-IQ-Plotter v3     (C) Andreas Dreier / Germany        Please don't hesitate to send me a mail   //
//                             andreas@dreier-privat.de        when you found errors or when you have    //
//   Plotter.BB8.c             21.11.2015                      ideas for improvements ;-)                //
//                                                                                                       //
///////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                       //
//   Necessary parts:                                                                                    //
//                                                                                                       //
//   1 x Super Kit       --> http://www.vexrobotics.com/vexiq/products/kits-bundles/super-kit-eu.html    //
//       P/N: 228-3670                                                                                   //
//                                                                                                       //
//   2 x Gear Add-On kit --> http://www.vexrobotics.com/vexiq/products/accessories/228-2532.html         //
//       P/N: 228-2532                                                                                   //
//                                                                                                       //
///////////////////////////////////////////////////////////////////////////////////////////////////////////


///////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                       //
//   Connections to the VEX-IQ brain:                                                                    //
//                                                                                                       //
//   Port   Type           Function                                                                      //
//   ----   ------------   -------------------------------------------------------------------           //
//    02    Motor          Movement x axis                                                               //
//    03    Touch sensor   Detecting right limitation of x axis                                          //
//    04    Touch sensor   Detecting bottom limitation of y axis                                         //
//    05    Motor          Movement y axis                                                               //
//    06    Motor          Movement pen up and down                                                      //
//                                                                                                       //
///////////////////////////////////////////////////////////////////////////////////////////////////////////

#include "plotBasics.inc"

///////////////////////////////////////////////////////////////////////////////////////////////////////////


float ms;
int   mx;
int   my;

///////////////////////////////////////////////////////////////////////////////////////////////////////////

void plotLine( int px, int py )
{
     plotLineTo( mx + ms * px, my + ms * py );
}

///////////////////////////////////////////////////////////////////////////////////////////////////////////

void plotMove( int px, int py )
{
     plotMoveTo( mx + ms * px, my + ms * py );
}

///////////////////////////////////////////////////////////////////////////////////////////////////////////

void plotBB8( int x, int y, float scale = 1.0 )
{
     ms = scale;
     mx = x;
     my = y;

     plotMove(   71,  413 );
     plotPenDown();
     plotLine(   77,  402 );
     plotLine(   84,  395 );
     plotLine(   94,  389 );
     plotLine(  106,  382 );
     plotLine(  119,  377 );
     plotLine(  136,  373 );
     plotLine(  155,  369 );
     plotLine(  178,  365 );
     plotLine(  202,  365 );
     plotLine(  225,  367 );
     plotLine(  247,  370 );
     plotLine(  268,  373 );
     plotLine(  287,  378 );
     plotLine(  306,  385 );
     plotLine(  318,  393 );
     plotLine(  326,  399 );
     plotLine(  332,  405 );
     plotLine(  336,  413 );
     plotLine(  334,  434 );
     plotLine(  331,  449 );
     plotLine(  327,  463 );
     plotLine(  320,  479 );
     plotLine(  311,  494 );
     plotLine(  299,  510 );
     plotLine(  284,  526 );
     plotLine(  272,  534 );
     plotLine(  251,  545 );
     plotLine(  235,  552 );
     plotLine(  222,  556 );
     plotLine(  209,  558 );
     plotLine(  195,  556 );
     plotLine(  186,  556 );
     plotLine(  171,  551 );
     plotLine(  155,  545 );
     plotLine(  135,  536 );
     plotLine(  124,  527 );
     plotLine(  117,  522 );
     plotLine(  112,  516 );
     plotLine(  105,  507 );
     plotLine(   94,  494 );
     plotLine(   85,  478 );
     plotLine(   80,  463 );
     plotLine(   75,  449 );
     plotLine(   73,  432 );
     plotLine(   72,  420 );
     plotLine(   73,  410 );
     plotPenUp();

     plotMove(  102,  385 );
     plotPenDown();
     plotLine(   89,  377 );
     plotLine(   73,  366 );
     plotLine(   57,  351 );
     plotLine(   47,  338 );
     plotLine(   35,  324 );
     plotLine(   28,  313 );
     plotLine(   21,  299 );
     plotLine(   12,  281 );
     plotLine(    5,  256 );
     plotLine(    1,  232 );
     plotLine(    0,  204 );
     plotLine(    3,  168 );
     plotLine(   10,  140 );
     plotLine(   21,  112 );
     plotLine(   37,   85 );
     plotLine(   45,   76 );
     plotLine(   61,   57 );
     plotLine(   81,   40 );
     plotLine(  103,   26 );
     plotLine(  132,   13 );
     plotLine(  160,    4 );
     plotLine(  185,    0 );
     plotLine(  214,    0 );
     plotLine(  240,    3 );
     plotLine(  259,    7 );
     plotLine(  268,   10 );
     plotLine(  283,   14 );
     plotLine(  293,   18 );
     plotLine(  311,   28 );
     plotLine(  331,   41 );
     plotLine(  340,   48 );
     plotLine(  357,   64 );
     plotLine(  368,   77 );
     plotLine(  381,   93 );
     plotLine(  388,  105 );
     plotLine(  391,  113 );
     plotLine(  399,  128 );
     plotLine(  410,  164 );
     plotLine(  414,  193 );
     plotLine(  413,  226 );
     plotLine(  407,  260 );
     plotLine(  400,  282 );
     plotLine(  384,  310 );
     plotLine(  369,  334 );
     plotLine(  352,  352 );
     plotLine(  332,  368 );
     plotLine(  319,  380 );
     plotLine(  306,  386 );
     plotPenUp();

     plotMove(   49,  251 );
     plotPenDown();
     plotLine(   37,  236 );
     plotLine(   28,  220 );
     plotLine(   21,  197 );
     plotLine(   19,  174 );
     plotLine(   22,  142 );
     plotLine(   27,  127 );
     plotLine(   35,  107 );
     plotLine(   43,   93 );
     plotLine(   50,   81 );
     plotLine(   67,   62 );
     plotLine(   83,   51 );
     plotLine(  109,   38 );
     plotLine(  136,   33 );
     plotLine(  157,   36 );
     plotLine(  173,   44 );
     plotLine(  191,   54 );
     plotLine(  207,   73 );
     plotLine(  218,   99 );
     plotLine(  224,  126 );
     plotLine(  223,  157 );
     plotLine(  216,  182 );
     plotLine(  207,  204 );
     plotLine(  198,  219 );
     plotLine(  177,  241 );
     plotLine(  153,  258 );
     plotLine(  128,  269 );
     plotLine(  103,  272 );
     plotLine(   84,  269 );
     plotLine(   70,  264 );
     plotLine(   49,  251 );
     plotPenUp();

     plotMove(   47,  152 );
     plotPenDown();
     plotLine(   51,  136 );
     plotLine(   54,  122 );
     plotLine(   62,  109 );
     plotLine(   70,   97 );
     plotLine(   81,   85 );
     plotLine(   96,   74 );
     plotLine(  104,   73 );
     plotLine(  111,  111 );
     plotLine(  127,  110 );
     plotLine(  132,   65 );
     plotLine(  151,   67 );
     plotLine(  165,   74 );
     plotLine(  181,   87 );
     plotLine(  189,  100 );
     plotLine(  194,  117 );
     plotLine(  159,  132 );
     plotLine(  160,  152 );
     plotLine(  198,  148 );
     plotLine(  193,  173 );
     plotLine(  182,  198 );
     plotLine(  169,  212 );
     plotLine(  155,  226 );
     plotLine(  137,  235 );
     plotLine(  131,  197 );
     plotLine(  116,  199 );
     plotLine(  113,  242 );
     plotLine(   96,  240 );
     plotLine(   77,  232 );
     plotLine(   63,  221 );
     plotLine(   54,  206 );
     plotLine(   46,  183 );
     plotLine(   84,  170 );
     plotLine(   84,  150 );
     plotLine(   47,  152 );
     plotPenUp();

     plotMove(  239,  369 );
     plotPenDown();
     plotLine(  238,  353 );
     plotLine(  241,  334 );
     plotLine(  246,  313 );
     plotLine(  253,  297 );
     plotLine(  262,  279 );
     plotLine(  271,  262 );
     plotLine(  286,  245 );
     plotLine(  304,  226 );
     plotLine(  324,  210 );
     plotLine(  350,  197 );
     plotLine(  365,  192 );
     plotLine(  379,  192 );
     plotLine(  389,  195 );
     plotLine(  396,  199 );
     plotLine(  403,  207 );
     plotLine(  408,  217 );
     plotLine(  412,  226 );
     plotPenUp();

     plotMove(  389,  279 );
     plotPenDown();
     plotLine(  389,  279 );
     plotLine(  384,  295 );
     plotLine(  376,  312 );
     plotLine(  362,  334 );
     plotLine(  347,  349 );
     plotLine(  330,  365 );
     plotLine(  329,  333 );
     plotLine(  317,  339 );
     plotLine(  308,  376 );
     plotLine(  293,  380 );
     plotPenUp();

     plotMove(  275,  375 );
     plotPenDown();
     plotLine(  268,  366 );
     plotLine(  263,  354 );
     plotLine(  263,  341 );
     plotLine(  295,  320 );
     plotLine(  295,  306 );
     plotLine(  266,  315 );
     plotLine(  275,  287 );
     plotLine(  288,  269 );
     plotLine(  296,  257 );
     plotLine(  308,  246 );
     plotLine(  325,  234 );
     plotLine(  324,  268 );
     plotLine(  337,  260 );
     plotLine(  346,  223 );
     plotLine(  358,  220 );
     plotLine(  369,  221 );
     plotLine(  381,  225 );
     plotLine(  388,  237 );
     plotLine(  392,  252 );
     plotLine(  359,  273 );
     plotLine(  358,  288 );
     plotLine(  389,  279 );
     plotPenUp();

     plotMove(  198,  219 );
     plotPenDown();
     plotLine(  212,  227 );
     plotLine(  229,  237 );
     plotLine(  244,  247 );
     plotLine(  258,  254 );
     plotLine(  271,  263 );
     plotPenUp();

     plotMove(   21,  300 );
     plotPenDown();
     plotLine(   32,  309 );
     plotLine(   43,  321 );
     plotLine(   62,  336 );
     plotLine(   77,  350 );
     plotLine(   92,  362 );
     plotLine(  104,  371 );
     plotLine(  118,  378 );
     plotPenUp();

     plotMove(   42,  321 );
     plotPenDown();
     plotLine(   40,  309 );
     plotLine(   40,  294 );
     plotLine(   42,  278 );
     plotLine(   45,  262 );
     plotLine(   48,  252 );
     plotPenUp();

     plotMove(  239,    4 );
     plotPenDown();
     plotLine(  245,   15 );
     plotLine(  252,   24 );
     plotLine(  264,   37 );
     plotLine(  279,   52 );
     plotLine(  298,   68 );
     plotLine(  317,   84 );
     plotLine(  335,   95 );
     plotLine(  353,  107 );
     plotLine(  371,  116 );
     plotLine(  386,  124 );
     plotLine(  397,  127 );
     plotPenUp();

     plotMove(  259,    9 );
     plotPenDown();
     plotLine(  262,   17 );
     plotLine(  271,   29 );
     plotLine(  286,   43 );
     plotLine(  295,   57 );
     plotLine(  308,   64 );
     plotLine(  315,   57 );
     plotLine(  331,   70 );
     plotLine(  333,   85 );
     plotLine(  347,   95 );
     plotLine(  361,  101 );
     plotLine(  374,  107 );
     plotLine(  382,  110 );
     plotLine(  388,  112 );
     plotPenUp();

     plotMove(  191,   55 );
     plotPenDown();
     plotLine(  207,   44 );
     plotLine(  216,   38 );
     plotLine(  229,   30 );
     plotLine(  241,   26 );
     plotLine(  251,   26 );
     plotPenUp();

     plotMove(  396,  128 );
     plotPenDown();
     plotLine(  398,  137 );
     plotLine(  401,  151 );
     plotLine(  401,  167 );
     plotLine(  400,  181 );
     plotLine(  399,  190 );
     plotLine(  395,  199 );
     plotPenUp();

     plotMove(   45,   75 );
     plotPenDown();
     plotLine(   49,   80 );
     plotPenUp();

     plotMove(  154,  545 );
     plotPenDown();
     plotLine(  168,  537 );
     plotLine(  180,  535 );
     plotLine(  199,  533 );
     plotLine(  216,  534 );
     plotLine(  236,  536 );
     plotLine(  249,  544 );
     plotPenUp();

     plotMove(  134,  534 );
     plotPenDown();
     plotLine(  143,  526 );
     plotLine(  157,  520 );
     plotLine(  170,  516 );
     plotLine(  184,  514 );
     plotLine(  205,  513 );
     plotLine(  221,  515 );
     plotLine(  238,  517 );
     plotLine(  252,  522 );
     plotLine(  264,  526 );
     plotLine(  273,  533 );
     plotPenUp();

     plotMove(  113,  515 );
     plotPenDown();
     plotLine(  123,  507 );
     plotLine(  133,  503 );
     plotLine(  147,  498 );
     plotLine(  163,  495 );
     plotLine(  176,  493 );
     plotLine(  182,  493 );
     plotLine(  188,  499 );
     plotLine(  169,  502 );
     plotLine(  153,  504 );
     plotLine(  143,  508 );
     plotLine(  130,  512 );
     plotLine(  122,  518 );
     plotLine(  115,  523 );
     plotPenUp();

     plotMove(  288,  522 );
     plotPenDown();
     plotLine(  281,  515 );
     plotLine(  270,  510 );
     plotLine(  259,  507 );
     plotLine(  245,  504 );
     plotLine(  252,  497 );
     plotLine(  264,  499 );
     plotLine(  277,  503 );
     plotLine(  284,  508 );
     plotLine(  294,  514 );
     plotPenUp();

     plotMove(  193,  463 );
     plotPenDown();
     plotLine(  199,  451 );
     plotLine(  207,  444 );
     plotLine(  219,  440 );
     plotLine(  231,  443 );
     plotLine(  242,  451 );
     plotLine(  248,  463 );
     plotLine(  248,  475 );
     plotLine(  243,  486 );
     plotLine(  233,  493 );
     plotLine(  220,  498 );
     plotLine(  208,  494 );
     plotLine(  197,  486 );
     plotLine(  191,  473 );
     plotLine(  193,  463 );
     plotPenUp();

     plotMove(  255,  434 );
     plotPenDown();
     plotLine(  257,  429 );
     plotLine(  264,  426 );
     plotLine(  272,  428 );
     plotLine(  276,  435 );
     plotLine(  277,  442 );
     plotLine(  274,  449 );
     plotLine(  267,  455 );
     plotLine(  258,  453 );
     plotLine(  253,  448 );
     plotLine(  252,  441 );
     plotLine(  256,  434 );
     plotPenUp();

     plotMove(   71,  421 );
     plotPenDown();
     plotLine(   81,  411 );
     plotLine(   95,  403 );
     plotLine(  111,  398 );
     plotLine(  133,  390 );
     plotLine(  156,  387 );
     plotLine(  175,  383 );
     plotLine(  196,  383 );
     plotLine(  221,  383 );
     plotLine(  246,  385 );
     plotLine(  272,  390 );
     plotLine(  294,  396 );
     plotLine(  313,  404 );
     plotLine(  326,  413 );
     plotLine(  335,  421 );
     plotPenUp();

     plotMove(   73,  433 );
     plotPenDown();
     plotLine(   83,  426 );
     plotLine(   92,  421 );
     plotLine(  102,  416 );
     plotLine(  116,  411 );
     plotLine(  135,  405 );
     plotLine(  148,  403 );
     plotLine(  159,  401 );
     plotLine(  168,  401 );
     plotLine(  184,  399 );
     plotLine(  204,  397 );
     plotLine(  231,  400 );
     plotLine(  259,  403 );
     plotLine(  286,  409 );
     plotLine(  302,  414 );
     plotLine(  314,  420 );
     plotLine(  322,  426 );
     plotLine(  329,  429 );
     plotLine(  334,  434 );
     plotPenUp();

     plotMove(   62,  119 );
     plotPenDown();
     plotLine(   92,  151 );
     plotLine(  114,  124 );
     plotLine(   83,   92 );
     plotLine(   62,  118 );
     plotPenUp();

     plotMove(   95,  157 );
     plotPenDown();
     plotLine(   94,  215 );
     plotLine(  109,  216 );
     plotLine(  109,  194 );
     plotLine(  135,  189 );
     plotLine(  139,  208 );
     plotLine(  164,  175 );
     plotLine(  151,  160 );
     plotLine(  143,  165 );
     plotLine(  132,  165 );
     plotLine(  129,  158 );
     plotLine(  130,  150 );
     plotLine(  134,  141 );
     plotLine(  121,  127 );
     plotLine(   95,  156 );
     plotPenUp();

     plotMove(  274,  346 );
     plotPenDown();
     plotLine(  303,  325 );
     plotLine(  301,  316 );
     plotLine(  303,  306 );
     plotLine(  306,  298 );
     plotLine(  315,  286 );
     plotLine(  321,  277 );
     plotLine(  334,  271 );
     plotLine(  346,  270 );
     plotLine(  351,  277 );
     plotLine(  350,  290 );
     plotLine(  346,  301 );
     plotLine(  339,  313 );
     plotLine(  328,  324 );
     plotLine(  320,  328 );
     plotLine(  311,  330 );
     plotLine(  299,  363 );
     plotLine(  295,  360 );
     plotLine(  297,  351 );
     plotLine(  296,  346 );
     plotLine(  292,  344 );
     plotLine(  286,  344 );
     plotLine(  279,  350 );
     plotLine(  274,  346 );
     plotPenUp();

     plotMove(  303,  323 );
     plotPenDown();
     plotLine(  346,  302 );
     plotPenUp();

     plotMove(  302,  311 );
     plotPenDown();
     plotLine(  350,  288 );
     plotPenUp();

     plotMove(  307,  297 );
     plotPenDown();
     plotLine(  347,  276 );
     plotPenUp();

     plotMove(  283,  355 );
     plotPenDown();
     plotLine(  288,  349 );
     plotLine(  291,  348 );
     plotLine(  293,  351 );
     plotLine(  288,  359 );
     plotLine(  282,  362 );
     plotLine(  282,  357 );
     plotLine(  284,  356 );
     plotPenUp();

     plotMove(  346,  262 );
     plotPenDown();
     plotLine(  353,  234 );
     plotLine(  365,  234 );
     plotLine(  372,  239 );
     plotLine(  378,  250 );
     plotLine(  356,  266 );
     plotLine(  347,  262 );
     plotPenUp();

     plotMove(  267,   11 );
     plotPenDown();
     plotLine(  267,   16 );
     plotLine(  271,   24 );
     plotLine(  276,   31 );
     plotLine(  322,   49 );
     plotLine(  321,   42 );
     plotLine(  326,   44 );
     plotLine(  341,   56 );
     plotLine(  337,   48 );
     plotPenUp();

     plotMove(  305,   29 );
     plotPenDown();
     plotLine(  302,   35 );
     plotLine(  267,   15 );
     plotPenUp();

     plotMove(  314,   51 );
     plotPenDown();
     plotLine(  329,   63 );
     plotLine(  345,   72 );
     plotLine(  356,   75 );
     plotLine(  357,   70 );
     plotLine(  356,   64 );
     plotLine(  346,   61 );
     plotLine(  333,   57 );
     plotLine(  315,   52 );
     plotPenUp();

     plotMove(  387,  106 );
     plotPenDown();
     plotLine(  366,  100 );
     plotLine(  351,   93 );
     plotLine(  339,   85 );
     plotLine(  338,   74 );
     plotLine(  363,   83 );
     plotLine(  379,   94 );
     plotPenUp();

     plotMove(  183,  403 );
     plotPenDown();
     plotLine(  182,  428 );
     plotLine(  162,  429 );
     plotLine(  145,  434 );
     plotLine(  144,  446 );
     plotLine(  162,  442 );
     plotLine(  183,  441 );
     plotLine(  184,  470 );
     plotLine(  188,  485 );
     plotLine(  197,  495 );
     plotLine(  208,  502 );
     plotLine(  226,  503 );
     plotLine(  238,  499 );
     plotLine(  248,  490 );
     plotLine(  254,  479 );
     plotLine(  255,  464 );
     plotLine(  272,  460 );
     plotLine(  280,  453 );
     plotLine(  284,  441 );
     plotLine(  284,  423 );
     plotLine(  284,  410 );
     plotPenUp();

     plotMove(  231,  401 );
     plotPenDown();
     plotLine(  228,  427 );
     plotLine(  209,  427 );
     plotLine(  182,  429 );
     plotLine(  182,  441 );
     plotPenUp();

     plotMove(  227,  428 );
     plotPenDown();
     plotLine(  229,  436 );
     plotLine(  238,  440 );
     plotLine(  247,  448 );
     plotLine(  252,  459 );
     plotLine(  254,  464 );
     plotPenUp();

     plotMove(  209,  410 );
     plotPenDown();
     plotLine(  215,  407 );
     plotLine(  221,  410 );
     plotLine(  223,  415 );
     plotLine(  222,  420 );
     plotLine(  216,  422 );
     plotLine(  210,  421 );
     plotLine(  207,  415 );
     plotLine(  208,  410 );
     plotPenUp();

     plotMove(   76,  449 );
     plotPenDown();
     plotLine(   84,  440 );
     plotLine(   84,  426 );
     plotPenUp();

     plotMove(   91,  423 );
     plotPenDown();
     plotLine(   91,  435 );
     plotLine(   96,  433 );
     plotLine(   95,  421 );
     plotPenUp();

     plotMove(  102,  417 );
     plotPenDown();
     plotLine(  103,  427 );
     plotLine(  119,  423 );
     plotLine(  135,  417 );
     plotLine(  135,  406 );
     plotPenUp();

     plotMove(  159,  403 );
     plotPenDown();
     plotLine(  160,  414 );
     plotLine(  169,  414 );
     plotLine(  167,  401 );
     plotPenUp();

     plotMove(  288,  412 );
     plotPenDown();
     plotLine(  286,  422 );
     plotLine(  299,  427 );
     plotLine(  300,  415 );
     plotPenUp();

     plotMove(  323,  427 );
     plotPenDown();
     plotLine(  321,  438 );
     plotLine(  326,  442 );
     plotLine(  327,  428 );
     plotPenUp();

     plotMove(  242,  216 );
     plotPenDown();
     plotLine(  249,  216 );
     plotLine(  254,  218 );
     plotLine(  252,  226 );
     plotLine(  248,  229 );
     plotLine(  241,  227 );
     plotLine(  239,  222 );
     plotLine(  241,  217 );
     plotPenUp();

     plotMove(  219,  252 );
     plotPenDown();
     plotLine(  224,  251 );
     plotLine(  229,  253 );
     plotLine(  230,  260 );
     plotLine(  227,  264 );
     plotLine(  222,  264 );
     plotLine(  217,  261 );
     plotLine(  217,  257 );
     plotLine(  220,  252 );
     plotLine(  221,  250 );
     plotPenUp();

     plotMove(   54,  291 );
     plotPenDown();
     plotLine(   59,  288 );
     plotLine(   64,  293 );
     plotLine(   64,  298 );
     plotLine(   60,  302 );
     plotLine(   56,  302 );
     plotLine(   52,  300 );
     plotLine(   52,  293 );
     plotLine(   55,  289 );
     plotPenUp();

     plotMove(   30,  271 );
     plotPenDown();
     plotLine(   32,  276 );
     plotLine(   32,  281 );
     plotLine(   27,  284 );
     plotLine(   22,  282 );
     plotLine(   22,  277 );
     plotLine(   22,  273 );
     plotLine(   26,  268 );
     plotLine(   31,  270 );
     plotLine(   31,  275 );
     plotPenUp();

     plotMove(  231,   47 );
     plotPenDown();
     plotLine(  234,   45 );
     plotLine(  240,   46 );
     plotLine(  243,   51 );
     plotLine(  241,   56 );
     plotLine(  235,   58 );
     plotLine(  230,   56 );
     plotLine(  229,   52 );
     plotLine(  231,   48 );
     plotLine(  234,   45 );
     plotPenUp();

     plotMove(  209,   11 );
     plotPenDown();
     plotLine(  211,   15 );
     plotLine(  211,   18 );
     plotLine(  208,   20 );
     plotLine(  201,   20 );
     plotLine(  201,   16 );
     plotLine(  203,   13 );
     plotLine(  208,   13 );
     plotPenUp();

     plotMove(  379,  155 );
     plotPenDown();
     plotLine(  385,  153 );
     plotLine(  389,  156 );
     plotLine(  391,  162 );
     plotLine(  386,  167 );
     plotLine(  381,  167 );
     plotLine(  378,  162 );
     plotLine(  378,  157 );
     plotLine(  381,  153 );
     plotPenUp();

     plotMove(  206,  560 );
     plotPenDown();
     plotLine(  206,  577 );
     plotLine(  207,  582 );
     plotLine(  211,  582 );
     plotLine(  211,  577 );
     plotLine(  211,  557 );
     plotPenUp();

     plotMove(  208,  585 );
     plotPenDown();
     plotPenUp();

     plotMove(  208,  632 );
     plotPenDown();
     plotLine(  206,  632 );
     plotLine(  206,  649 );
     plotLine(  209,  652 );
     plotLine(  211,  650 );
     plotLine(  211,  631 );
     plotLine(  207,  631 );
     plotPenUp();

     plotMove(  184,  557 );
     plotPenDown();
     plotPenUp();

     plotMove(  183,  557 );
     plotPenDown();
     plotLine(  183,  576 );
     plotLine(  186,  606 );
     plotLine(  187,  578 );
     plotLine(  187,  558 );
     plotPenUp();

}


///////////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
     // Initialize the plotter

     plotInit();

     plotBB8( 200, 200, 1.0 );

     // Move back to home position

     plotMoveHome();
}

//---------------------------------------------------------------------------------------------------------
//   Plotter.Minion.c    ---   End of program
//---------------------------------------------------------------------------------------------------------
