def deliver_to(red, green, blue):
    if blue:
        drivetrain.turn_for(RIGHT, 90, DEGREES)
        drivetrain.drive_for(FORWARD, 800, MM)
        drivetrain.turn_for(LEFT, 90, DEGREES)
        drivetrain.drive_for(FORWARD, 200, MM)
        magnet.energize(DROP)
        drivetrain.drive_for(REVERSE, 200, MM)
        drivetrain.turn_for(RIGHT, 90, DEGREES)
        drivetrain.drive_for(REVERSE, 800, MM)
        drivetrain.turn_for(LEFT, 90, DEGREES)
    if red:
        drivetrain.drive_for(FORWARD, 200, MM)
        magnet.energize(DROP)
        drivetrain.drive_for(REVERSE, 200, MM)
    if green:
        drivetrain.turn_for(LEFT, 90, DEGREES)
        drivetrain.drive_for(FORWARD, 800, MM)
        drivetrain.turn_for(RIGHT, 90, DEGREES)
        drivetrain.drive_for(FORWARD, 200, MM)
        magnet.energize(DROP)
        drivetrain.drive_for(REVERSE, 200, MM)
        drivetrain.turn_for(LEFT, 90, DEGREES)
        drivetrain.drive_for(REVERSE, 800, MM)
        drivetrain.turn_for(RIGHT, 90, DEGREES)

def when_started():
    drivetrain.set_turn_velocity(100, PERCENT)
    drivetrain.set_drive_velocity(100, PERCENT)
    # Row 1
    drivetrain.drive_for(FORWARD, 700, MM)
    drivetrain.turn_for(RIGHT, 90, DEGREES)
    drivetrain.drive_for(FORWARD, 240, MM)
    magnet.energize(BOOST)
    drivetrain.drive_for(REVERSE, 240, MM)
    drivetrain.turn_for(RIGHT, 90, DEGREES)
    drivetrain.drive_for(FORWARD, 400, MM)
    deliver_to(False, True, False)
    drivetrain.drive_for(REVERSE, 400, MM)
    drivetrain.turn_for(LEFT, 90, DEGREES)
    drivetrain.drive_for(FORWARD, 440, MM)
    magnet.energize(BOOST)
    drivetrain.drive_for(REVERSE, 440, MM)
    drivetrain.turn_for(RIGHT, 90, DEGREES)
    drivetrain.drive_for(FORWARD, 400, MM)
    deliver_to(False, True, False)
    drivetrain.drive_for(REVERSE, 400, MM)
    drivetrain.turn_for(RIGHT, 90, DEGREES)
    drivetrain.drive_for(FORWARD, 240, MM)
    magnet.energize(BOOST)
    drivetrain.drive_for(REVERSE, 240, MM)
    drivetrain.turn_for(LEFT, 90, DEGREES)
    drivetrain.drive_for(FORWARD, 400, MM)
    deliver_to(False, False, True)
    drivetrain.drive_for(REVERSE, 400, MM)
    drivetrain.turn_for(RIGHT, 90, DEGREES)
    drivetrain.drive_for(FORWARD, 440, MM)
    magnet.energize(BOOST)
    drivetrain.drive_for(REVERSE, 440, MM)
    drivetrain.turn_for(LEFT, 90, DEGREES)
    drivetrain.drive_for(FORWARD, 400, MM)
    deliver_to(False, False, True)
    # Row 2
    drivetrain.drive_for(REVERSE, 600, MM)
    drivetrain.turn_for(LEFT, 90, DEGREES)
    drivetrain.drive_for(FORWARD, 440, MM)
    magnet.energize(BOOST)
    drivetrain.drive_for(REVERSE, 440, MM)
    drivetrain.turn_for(RIGHT, 90, DEGREES)
    drivetrain.drive_for(FORWARD, 600, MM)
    deliver_to(False, False, True)
    drivetrain.drive_for(REVERSE, 600, MM)
    drivetrain.turn_for(RIGHT, 90, DEGREES)
    drivetrain.drive_for(FORWARD, 440, MM)
    magnet.energize(BOOST)
    drivetrain.drive_for(REVERSE, 440, MM)
    drivetrain.turn_for(LEFT, 90, DEGREES)
    drivetrain.drive_for(FORWARD, 600, MM)
    deliver_to(True, False, False)
    # Row 3
    drivetrain.drive_for(REVERSE, 600, MM)
    drivetrain.turn_for(RIGHT, 90, DEGREES)
    drivetrain.drive_for(FORWARD, 500, MM)
    drivetrain.turn_for(RIGHT, 90, DEGREES)
    drivetrain.drive_for(FORWARD, 140, MM)
    magnet.energize(BOOST)
    drivetrain.drive_for(REVERSE, 140, MM)
    drivetrain.turn_for(LEFT, 90, DEGREES)
    drivetrain.drive_for(REVERSE, 500, MM)
    drivetrain.turn_for(LEFT, 90, DEGREES)
    drivetrain.drive_for(FORWARD, 600, MM)
    deliver_to(True, False, False)
    drivetrain.drive_for(REVERSE, 600, MM)
    drivetrain.turn_for(LEFT, 90, DEGREES)
    drivetrain.drive_for(FORWARD, 500, MM)
    drivetrain.turn_for(LEFT, 90, DEGREES)
    drivetrain.drive_for(FORWARD, 140, MM)
    magnet.energize(BOOST)
    drivetrain.drive_for(REVERSE, 140, MM)
    drivetrain.turn_for(RIGHT, 90, DEGREES)
    drivetrain.drive_for(REVERSE, 500, MM)
    drivetrain.turn_for(RIGHT, 90, DEGREES)
    drivetrain.drive_for(FORWARD, 600, MM)
    deliver_to(False, False, True)
    # Row 4
    drivetrain.drive_for(REVERSE, 600, MM)
    drivetrain.turn_for(LEFT, 90, DEGREES)
    drivetrain.drive_for(FORWARD, 500, MM)
    drivetrain.turn_for(LEFT, 90, DEGREES)
    drivetrain.drive_for(FORWARD, 340, MM)
    magnet.energize(BOOST)
    drivetrain.drive_for(REVERSE, 340, MM)
    drivetrain.turn_for(RIGHT, 90, DEGREES)
    drivetrain.drive_for(REVERSE, 500, MM)
    drivetrain.turn_for(RIGHT, 90, DEGREES)
    drivetrain.drive_for(FORWARD, 600, MM)
    deliver_to(True, False, False)
    drivetrain.drive_for(REVERSE, 600, MM)
    drivetrain.turn_for(LEFT, 90, DEGREES)
    drivetrain.drive_for(FORWARD, 300, MM)
    drivetrain.turn_for(LEFT, 90, DEGREES)
    drivetrain.drive_for(FORWARD, 340, MM)
    magnet.energize(BOOST)
    drivetrain.drive_for(REVERSE, 340, MM)
    drivetrain.turn_for(RIGHT, 90, DEGREES)
    drivetrain.drive_for(REVERSE, 300, MM)
    drivetrain.turn_for(RIGHT, 90, DEGREES)
    drivetrain.drive_for(FORWARD, 600, MM)
    deliver_to(True, False, False)
    drivetrain.drive_for(REVERSE, 600, MM)
    drivetrain.turn_for(RIGHT, 90, DEGREES)
    drivetrain.drive_for(FORWARD, 500, MM)
    drivetrain.turn_for(RIGHT, 90, DEGREES)
    drivetrain.drive_for(FORWARD, 340, MM)
    magnet.energize(BOOST)
    drivetrain.drive_for(REVERSE, 340, MM)
    drivetrain.turn_for(LEFT, 90, DEGREES)
    drivetrain.drive_for(REVERSE, 500, MM)
    drivetrain.turn_for(LEFT, 90, DEGREES)
    drivetrain.drive_for(FORWARD, 600, MM)
    deliver_to(False, True, False)
    drivetrain.drive_for(REVERSE, 600, MM)
    drivetrain.turn_for(RIGHT, 90, DEGREES)
    drivetrain.drive_for(FORWARD, 300, MM)
    drivetrain.turn_for(RIGHT, 90, DEGREES)
    drivetrain.drive_for(FORWARD, 340, MM)
    magnet.energize(BOOST)
    drivetrain.drive_for(REVERSE, 340, MM)
    drivetrain.turn_for(LEFT, 90, DEGREES)
    drivetrain.drive_for(REVERSE, 300, MM)
    drivetrain.turn_for(LEFT, 90, DEGREES)
    drivetrain.drive_for(FORWARD, 600, MM)
    deliver_to(False, True, False)

vr_thread(when_started())
