def when_started():
    # Run on the Art Canvas Playground :)
    drivetrain.drive_for(FORWARD, 800, MM)
    drivetrain.turn_for(LEFT, 90, DEGREES)
    drivetrain.drive_for(FORWARD, 800, MM)
    pen.move(DOWN)
    drivetrain.turn_for(LEFT, 90, DEGREES)
    drivetrain.drive_for(FORWARD, 800, MM)
    drivetrain.drive_for(REVERSE, 400, MM)
    drivetrain.turn_for(LEFT, 90, DEGREES)
    drivetrain.drive_for(FORWARD, 300, MM)
    drivetrain.turn_for(RIGHT, 90, DEGREES)
    drivetrain.drive_for(REVERSE, 400, MM)
    drivetrain.drive_for(FORWARD, 800, MM)
    pen.move(UP)
    drivetrain.turn_for(LEFT, 90, DEGREES)
    drivetrain.drive_for(FORWARD, 100, MM)
    drivetrain.turn_for(LEFT, 90, DEGREES)
    drivetrain.drive_for(FORWARD, 200, MM)
    drivetrain.turn_for(RIGHT, 90, DEGREES)
    pen.move(DOWN)
    drivetrain.drive_for(FORWARD, 275, MM)
    drivetrain.turn_for(LEFT, 90, DEGREES)
    for repeat_count in range(17):
        drivetrain.turn_for(LEFT, 20, DEGREES)
        drivetrain.drive_for(FORWARD, 50, MM)
        wait(5, MSEC)
    pen.move(UP)
    drivetrain.turn_for(RIGHT, 90, DEGREES)
    drivetrain.drive_for(FORWARD, 75, MM)
    drivetrain.turn_for(LEFT, 110, DEGREES)
    drivetrain.drive_for(REVERSE, 120, MM)
    pen.move(DOWN)
    drivetrain.drive_for(FORWARD, 800, MM)
    pen.move(UP)
    drivetrain.turn_for(RIGHT, 90, DEGREES)
    drivetrain.drive_for(FORWARD, 120, MM)
    drivetrain.turn_for(RIGHT, 90, DEGREES)
    pen.move(DOWN)
    drivetrain.drive_for(FORWARD, 800, MM)
    drivetrain.turn_for(LEFT, 90, DEGREES)
    pen.move(UP)
    drivetrain.drive_for(FORWARD, 300, MM)
    pen.move(DOWN)
    for repeat_count2 in range(20):
        drivetrain.turn_for(LEFT, 20, DEGREES)
        drivetrain.drive_for(FORWARD, 50, MM)
        wait(5, MSEC)
    pen.move(UP)
    drivetrain.turn_for(RIGHT, 90, DEGREES)
    drivetrain.drive_for(FORWARD, 200, MM)

vr_thread(when_started())
