def when_started():
    drivetrain.drive_for(FORWARD, 800, MM)
    drivetrain.turn_for(LEFT, 90, DEGREES)
    drivetrain.drive_for(FORWARD, 800, MM)
    pen.move(DOWN)
    drivetrain.turn_for(LEFT, 110, DEGREES)
    drivetrain.drive_for(FORWARD, 800, MM)
    drivetrain.turn_for(LEFT, 140, DEGREES)
    drivetrain.drive_for(FORWARD, 800, MM)
    pen.move(UP)
    drivetrain.turn_for(RIGHT, 70, DEGREES)
    drivetrain.drive_for(FORWARD, 200, MM)
    pen.move(DOWN)
    drivetrain.drive_for(FORWARD, 300, MM)
    drivetrain.drive_for(REVERSE, 300, MM)
    drivetrain.turn_for(RIGHT, 90, DEGREES)
    drivetrain.drive_for(FORWARD, 375, MM)
    drivetrain.turn_for(LEFT, 90, DEGREES)
    drivetrain.drive_for(FORWARD, 300, MM)
    drivetrain.drive_for(REVERSE, 300, MM)
    drivetrain.turn_for(RIGHT, 90, DEGREES)
    drivetrain.drive_for(FORWARD, 375, MM)
    drivetrain.turn_for(LEFT, 90, DEGREES)
    drivetrain.drive_for(FORWARD, 300, MM)
    pen.move(UP)
    drivetrain.drive_for(FORWARD, 200, MM)
    pen.move(DOWN)
    drivetrain.turn_for(LEFT, 70, DEGREES)
    drivetrain.drive_for(FORWARD, 800, MM)
    drivetrain.turn_for(LEFT, 110, DEGREES)
    pen.move(UP)
    drivetrain.drive_for(FORWARD, 270, MM)
    pen.move(DOWN)
    drivetrain.turn_for(LEFT, 110, DEGREES)
    drivetrain.drive_for(FORWARD, 800, MM)

vr_thread(when_started())
