#pragma config(Sensor, port3,  EndX,           sensorVexIQ_Touch)
#pragma config(Sensor, port4,  EndY,           sensorVexIQ_Touch)
#pragma config(Motor,  motor2,          MotorX,        tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor5,          MotorY,        tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          MotorPen,      tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

///////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                       //
//   VEX-IQ-Plotter v3     (C) Andreas Dreier / Germany        Please don't hesitate to send me a mail   //
//                             andreas@dreier-privat.de        when you found errors or when you have    //
//   Plotter.Demo2.c           25.08.2015                      ideas for improvements ;-)                //
//                                                                                                       //
///////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                       //
//   Necessary parts:                                                                                    //
//                                                                                                       //
//   1 x Super Kit       --> http://www.vexrobotics.com/vexiq/products/kits-bundles/super-kit-eu.html    //
//       P/N: 228-3670                                                                                   //
//                                                                                                       //
//   2 x Gear Add-On kit --> http://www.vexrobotics.com/vexiq/products/accessories/228-2532.html         //
//       P/N: 228-2532                                                                                   //
//                                                                                                       //
///////////////////////////////////////////////////////////////////////////////////////////////////////////


///////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                       //
//   Connections to the VEX-IQ brain:                                                                    //
//                                                                                                       //
//   Port   Type           Function                                                                      //
//   ----   ------------   -------------------------------------------------------------------           //
//    02    Motor          Movement x axis                                                               //
//    03    Touch sensor   Detecting right limitation of x axis                                          //
//    04    Touch sensor   Detecting bottom limitation of y axis                                         //
//    05    Motor          Movement y axis                                                               //
//    06    Motor          Movement pen up and down                                                      //
//                                                                                                       //
///////////////////////////////////////////////////////////////////////////////////////////////////////////

#include "plotBasics.inc"

#include "plotGraphics.inc"

#include "plotText.inc"

///////////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
     plotInit();                                              // Initialize the plotter

     plotRectangle( 400, 400,    200, 200 );                  // Plot a rectangle between points 400/400 and 200/200
     plotLine(      400, 400,    200, 200 );                  // Plot a line between points 400/400 and 200/200
     plotCircle(    300, 550,    100 );                       // Plot a circle at position 300/550 with radius of 100
     plotTriangle(  650, 450,    450, 450,    550, 650 );     // Plot a triangle with points 650/450, 450/450 and 550,650
     plotNEdge(     550, 300,    100,     6,     30 );        // Plot a figure with 6 edges at 550/300 and radius of 100 and rotate by 30°

     plotText( 800, 800, 20, FONT_DIRECTION_LR, " ABC" );     // Plot „ ABC“ at 800,800 with size of 20 from left to right
     plotText( 800, 800, 20, FONT_DIRECTION_RL, " XYZ" );     // Plot „ XYZ“ at 800,800 with size of 20 from right to left
     plotText( 800, 800, 20, FONT_DIRECTION_BT, " 123" );     // Plot „ 123“ at 800,800 with size of 20 from bottom to top
     plotText( 800, 800, 20, FONT_DIRECTION_TB, " 890" );     // Plot „ 890“ at 800,800 with size of 20 from top to bottom

     plotMoveTo( 700,400 );                                   // Move pen to position 700,400
     plotPenDown();                                           // Put the pen on the paper
     plotLineTo( 1000,500 );                                  // Plot a direct line to 1000,500 (very slow)
     plotMoveTo( 700,400 );                                   // Move back to 700,400 (very fast – and not on a line!)
     plotPenUp();                                             // Lift the pen up from paper

     plotMoveHome();                                          // Move back to home position
}

//---------------------------------------------------------------------------------------------------------
//   Plotter.Demo2.c    ---   End of program
//---------------------------------------------------------------------------------------------------------
