#pragma config(Sensor, port3,  EndX,           sensorVexIQ_Touch)
#pragma config(Sensor, port4,  EndY,           sensorVexIQ_Touch)
#pragma config(Motor,  motor2,          MotorX,        tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor5,          MotorY,        tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          MotorPen,      tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

///////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                       //
//   VEX-IQ-Plotter v3     (C) Andreas Dreier / Germany        Please don't hesitate to send me a mail   //
//                             andreas@dreier-privat.de        when you found errors or when you have    //
//   Plotter.Demo1.c           25.08.2015                      ideas for improvements ;-)                //
//                                                                                                       //
///////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                       //
//   Necessary parts:                                                                                    //
//                                                                                                       //
//   1 x Super Kit       --> http://www.vexrobotics.com/vexiq/products/kits-bundles/super-kit-eu.html    //
//       P/N: 228-3670                                                                                   //
//                                                                                                       //
//   2 x Gear Add-On kit --> http://www.vexrobotics.com/vexiq/products/accessories/228-2532.html         //
//       P/N: 228-2532                                                                                   //
//                                                                                                       //
///////////////////////////////////////////////////////////////////////////////////////////////////////////


///////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                       //
//   Connections to the VEX-IQ brain:                                                                    //
//                                                                                                       //
//   Port   Type           Function                                                                      //
//   ----   ------------   -------------------------------------------------------------------           //
//    02    Motor          Movement x axis                                                               //
//    03    Touch sensor   Detecting right limitation of x axis                                          //
//    04    Touch sensor   Detecting bottom limitation of y axis                                         //
//    05    Motor          Movement y axis                                                               //
//    06    Motor          Movement pen up and down                                                      //
//                                                                                                       //
///////////////////////////////////////////////////////////////////////////////////////////////////////////

#include "plotBasics.inc"

///////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                       //
//   Starting from here you could implement your own coding                                              //
//                                                                                                       //
///////////////////////////////////////////////////////////////////////////////////////////////////////////

#include "plotGraphics.inc"

#include "plotText.inc"

///////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                       //
//   Main program - insert your own code before and call it from main program                            //
//                                                                                                       //
//   Please keep in mind that you call first the function plotInit() before you execute your own         //
//   function                                                                                            //
//                                                                                                       //
///////////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
     // Initialize the plotter

     plotInit();

     // Plot some basic figures

     plotText( 1000, 1500, 20, FONT_DIRECTION_TB, "Oscar" );
     plotText(  800, 1500, 20, FONT_DIRECTION_TB, "Leslie" )

     plotText(  600, 1500, 20, FONT_DIRECTION_TB, "Oscar" );
     plotText(  400, 1500, 20, FONT_DIRECTION_TB, "Duggleby" );



     // Move back to home position

     plotMoveHome();
}

//---------------------------------------------------------------------------------------------------------
//   Plotter.Demo1.c    ---   End of program
//---------------------------------------------------------------------------------------------------------
