#pragma config(Sensor, port3,  EndX,           sensorVexIQ_Touch)
#pragma config(Sensor, port4,  EndY,           sensorVexIQ_Touch)
#pragma config(Motor,  motor2,          MotorX,        tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor5,          MotorY,        tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          MotorPen,      tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

///////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                       //
//   VEX-IQ-Plotter v3     (C) Andreas Dreier / Germany        Please don't hesitate to send me a mail   //
//                             andreas@dreier-privat.de        when you found errors or when you have    //
//   Plotter.Template.c        21.11.2015                      ideas for improvements ;-)                //
//                                                                                                       //
///////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                       //
//   Necessary parts:                                                                                    //
//                                                                                                       //
//   1 x Super Kit       --> http://www.vexrobotics.com/vexiq/products/kits-bundles/super-kit-eu.html    //
//       P/N: 228-3670                                                                                   //
//                                                                                                       //
//   2 x Gear Add-On kit --> http://www.vexrobotics.com/vexiq/products/accessories/228-2532.html         //
//       P/N: 228-2532                                                                                   //
//                                                                                                       //
///////////////////////////////////////////////////////////////////////////////////////////////////////////


///////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                       //
//   Connections to the VEX-IQ brain:                                                                    //
//                                                                                                       //
//   Port   Type           Function                                                                      //
//   ----   ------------   -------------------------------------------------------------------           //
//    02    Motor          Movement x axis                                                               //
//    03    Touch sensor   Detecting right limitation of x axis                                          //
//    04    Touch sensor   Detecting bottom limitation of y axis                                         //
//    05    Motor          Movement y axis                                                               //
//    06    Motor          Movement pen up and down                                                      //
//                                                                                                       //
///////////////////////////////////////////////////////////////////////////////////////////////////////////

#include "plotBasics.inc"

///////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                       //
//   Starting from here you could implement your own coding                                              //
//   Alternatively you could also use the pre-defined commands                                           //
//                                                                                                       //
//     plotBasics.inc:                                                                                   //
//                                                                                                       //
//       plotPenDown()                          Move the pon down on paper                               //
//       plotPenUp()                            Raise the pen up                                         //
//       plotMoveTo( posx, posy )               Move the pen on fastest way to the coordinate            //
//       plotLineTo( posx, posy )               Move the pen on a direct line to new position            //
//                                                                                                       //
//                                                                                                       //
//     plotGraphics.inc                                                                                  //
//                                                                                                       //
//       plotLine( x1,y1, x2,y2 )               Plot a line between the two given coordinates            //
//       plotRectangle( x1,y1, x2,y2 )          Plot a rectangle between the two given coordinates       //
//       plotTriange( x1,y1, x2,y2, x3,y3 )     Plot a triangle between the three given coordinates      //
//       plotNEdge( x,y, radius, edges, angle ) Plot a figure with n edges and center position x/y       //
//                                              using given radius and starting with given angle         //
//                                                e.g.  plotNEdge( -500,500, 50, 4, 45 )                 //
//       plotCircle( x,y, radius )              Plot a circle with given radius at position x/y          //
//                                                                                                       //
//       Please add the following line to your program when you plan to use the graphics functions:      //
//                                                                                                       //
//       #include "plotGraphics.inc"                                                                     //
//                                                                                                       //
//     plotText.inc                                                                                      //
//                                                                                                       //
//       plotText( x,y, size, direction, text ) Plot the given text at given position with given size    //
//                                              to the one of the 4 possible directions:                 //
//                                                  FONT_DIRECTION_LR      From left to right            //
//                                                  FONT_DIRECTION_RL      From right to left            //
//                                                  FONT_DIRECTION_BT      From bottom to top            //
//                                                  FONT_DIRECTION_TB      FROM top to bottom            //
//                                                e.g. plotText( -1000,200,20,FONT_DIRECTION_LR,"Hello") //
//                                                                                                       //
//       Please add the following line to your program when you plan to use the plotText function:       //
//                                                                                                       //
//       #include "plotText.inc"                                                                         //
//                                                                                                       //
//  Please keep in mind the coordination system of the plotter:                                          //
//                                                                        x-value should be in the       //
//       +----------------------------------------------------+           range of 0 and 2250            //
//       |               paper_top           :                | 2150                                     //
//       |                                   :                |                  0 <= x <= 2250          //
//       |                                   :                |                                          //
//       |                                   :                |                                          //
//       |                                   :                |           y-value should be in the       //
//       |                                   :                |           range of 0 and 2150            //
//       |                                   :                |                                          //
//       |                                   :                |                  0 <= y <= 2150          //
//       |                                   :                |                                          //
//       |                                   :                |                                          //
//       |                                   :                |                                          //
//       |paper_left              paper-right:                |                                          //
//       |                                   :                |                                          //
//       |                                   :                |                                          //
//       |                                   :                |                                          //
//       |                                   :                |                                          //
//       |                                   :                |                                          //
//       |                                   :                |                                          //
//       |                                   :                |                                          //
//       |                                   :                |                                          //
//       |                                   :                |                                          //
//       |                                   :                |                                          //
//       |           paper_bottom            :                |                                          //
//       +----------------------------------------------------+ 0                                        //
//     -2250                                                  0                                          //
//                                                                                                       //
///////////////////////////////////////////////////////////////////////////////////////////////////////////

#include "plotGraphics.inc"

void example()
{
     // Following two command sequences are doing the same: plotting a line between two points

     // Basic method:

     plotMoveTo( 500, 500 );
     plotPenDown();
     plotLineTo( 550, 600 );
     plotPenUp();

     // Graphical method:

     plotLine( 500, 500,
               550, 600 );
}


///////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                       //
//   Main program - insert your own code before and call it from main program                            //
//                                                                                                       //
//   Please keep in mind that you call first the function plotInit() before you execute your own         //
//   function                                                                                            //
//                                                                                                       //
///////////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
     // Initialize the plotter

     plotInit();

     //    |  |      insert your own coding between the two arrows
     //    |  |
     //  __|  |__
     //  \      /
     //   \    /
     //    \  /
     //     \/


     example();


     //     /\
     //    /  \
     //   /    \
     //  /_    _\
     //    |  |
     //    |  |
     //    |  |

     // Move back ot parking position (bottom right corner)

     plotMoveHome();
}

//---------------------------------------------------------------------------------------------------------
//   Plotter.Template.c    ---   End of program
//---------------------------------------------------------------------------------------------------------
